# Ejercicio: Extracción de datos de la API de TMDB (The Movie Database)

![imagen](https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg)

Trabajaremos con **TMDB**, una de las bases de datos de cine más importantes del mundo. El objetivo es extraer información de películas para realizar un análisis de mercado inicial.

### 1. Registro y Documentación
Tendrás que [registrarte en TMDB](https://www.themoviedb.org/signup) para obtener tu **API Key (v3 auth)** y consultar la [documentación oficial](https://developer.themoviedb.org/reference/intro/getting-started).

### 2. Objetivo del Ejercicio
Queremos que consultes la API para que te devuelva la información de las películas que empiecen por la **inicial de tu nombre** (parámetro `query`). 

Debes guardar la información en un archivo `.csv` con la siguiente estructura de columnas:

| Columna | Descripción |
| :--- | :--- |
| **id** | ID interno de la película en TMDB |
| **title** | Título de la película |
| **release_date** | Fecha de estreno |
| **genres** | Nombres de los géneros (ej: "Acción, Comedia") |
| **vote_average** | Puntuación media de los usuarios |
| **overview** | Sinopsis o resumen de la trama |

### 3. El Reto: Mapeo de Géneros
A diferencia de otras APIs, el endpoint de búsqueda de películas devuelve los géneros como una lista de IDs numéricos (ej: `[28, 12]`). 

**Tu labor es:**
1. Consultar el endpoint de "Genre List" para obtener la relación entre IDs y nombres.
2. Sustituir los IDs en tu DataFrame final por los nombres reales de los géneros (separados por comas).

---

### Código de inicio
Aquí tienes el bloque para empezar a configurar tus llamadas:

```python
import requests
import pandas as pd

# Rellena estas variables
api_key = "TU_API_KEY_AQUÍ"
url_base = "[https://api.themoviedb.org/3](https://api.themoviedb.org/3)"
mi_inicial = "P" # Sustituye por tu inicial

In [2]:
import requests
import pandas as pd

# Configuración
api_key = "930590f441225ca054ca5c0d0a53220e"
url_base = "https://api.themoviedb.org/3"
mi_inicial = "u" # Cambiar por la inicial del alumno
genres = '/genre/movie/list?'
search = '/search/movie?'

In [67]:
# 1. Obtener el diccionario de géneros (ID -> Nombre)
# Tip: Endpoint /genre/movie/list
def get_genres_map(api_key):
    url = url_base + genres + 'api_key=' + api_key
    response = requests.get(url)

    if response.status_code == 200:  # Código 200 indica una respuesta exitosa.
        data = response.json()  # Analizar la respuesta JSON.
    else:
        print("Error en la solicitud: ", response.status_code)
        return
    
    # Guardamos los id de géneros
    generos = {}

    for genre in data['genres']:
        # nombre = genre['name']
        generos[genre['id']] = genre['name']

    return generos


# 2. Buscar películas
# Tip: Endpoint /search/movie
def search_movies(api_key, query, page = 1):
    # Metemos paginado para recuperar las películas de cada página
    url = url_base + search + 'query=' + query + '&page=' + str(page) + '&api_key=' + api_key
    # print(url) # imprimimos para pruebas
    response = requests.get(url)

    if response.status_code == 200:  # Código 200 indica una respuesta exitosa.
        data = response.json()  # Analizar la respuesta JSON.
        return data
    else:
        print("Error en la solicitud: ", response.status_code)
        return


# 3. Procesamiento y Limpieza
def busca_pelis(api_key, query):
    # Búsqueda inicial de películas
    data = search_movies(api_key, query)
    # Recuperamos los géneros de películas
    genres_dict = get_genres_map(api_key)
    
    # Recuperamos total páginas para saber si hay más de una
    pages = data['total_pages']
    lista_pelis = []
    if pages > 1:
        # Bucle de páginas
        for pag in range(pages):
            data = search_movies(api_key, query, page=pag + 1) # range(pages) comienza desde 0 hasta page - 1, sumamos 1
            lista_pelis = guardar_pelis(data, lista_pelis, genres_dict)
    
    else: # Si solo hay una página
        lista_pelis = guardar_pelis(data, lista_pelis)

            
    return lista_pelis


def guardar_pelis(movies, lista_pelis, genres_dict):
    # Bucle por película de la página
    for peli in movies['results']:
        pel = {
            'id' : 0,
            'title' : '',
            'release_date' : '',
            'genres' : [],
            'vote_average' : 0.0,
            'overview' : ''
        }
        pel['id'] = peli['id']
        pel['title'] = peli['title']
        pel['release_date'] = peli['release_date']
        # - Mapear los IDs de géneros a nombres reales.
        for genre in peli['genre_ids']: # Lista géneros
            genero = genres_dict[genre]
            pel['genres'].append(genero)
        pel['vote_average'] = peli['vote_average']
        pel['overview'] = peli['overview']
        lista_pelis.append(pel)
    return lista_pelis


def limpiar_lista_pelis(lista_pelis, mi_inicial):
    lista_limpia = []
    for movie in lista_pelis:
        if movie['title'][0] not in ('U','u'): # title: 'U...'
            continue
        
        lista_limpia.append(movie)
    return lista_limpia


# - Crear el DataFrame.
def lista2df(lista):
    df = pd.DataFrame(lista)
    return df


# - Exportar a CSV.
def export_csv(df, nombre):
    df.to_csv('./data/' + nombre + '.csv', index=False)

In [ ]:
# Pruebo el buscador de géneros
genres_dict = get_genres_map(api_key)
genres_dict

In [ ]:
# Creamos lista vacía y metemos las películas
lista_pelis = []
lista_pelis = busca_pelis(api_key, mi_inicial)
lista_pelis

[{'id': 39405,
  'title': 'U',
  'release_date': '2006-10-11',
  'genres': ['Animation', 'Fantasy'],
  'vote_average': 6.6,
  'overview': "Since her parents passed away, Princess Mona lives by herself in a castle with two hideous, ghastly characters, Goomi and His Lordship. One day her sobs draw the attention of a unicorn, called U, who wants to comfort and protect Mona for as long as she needs. U becomes Mona's companion, her confidant and her inseparable friend. While Mona grows into a beautiful princess, a group of charming, peaceful and fanciful Yeah-Yeah’s settles in the neighboring forest. They have no particular special powers, yet they soon bring about major changes in everyone's lives, especially in Kulka, the dreamy musician."},
 {'id': 1499984,
  'title': 'Gladiator Underground',
  'release_date': '2025-08-22',
  'genres': ['Action'],
  'vote_average': 7.4,
  'overview': "Two brothers compete in the world's deadliest underground fighting tournament, where they must decide whether to play by the rules or to cast their honor aside and team up to bring down the dark syndicate running the tournament."},
 {'id': 335,
  'title': 'Once Upon a Time in the West',
  'release_date': '1968-12-21',
  'genres': ['Drama', 'Western'],
  'vote_average': 8.276,
  'overview': 'As the railroad builders advance unstoppably through the Arizona desert on their way to the sea, Jill arrives in the small town of Flagstone with the intention of starting a new life.'},
 {'id': 1303795,
  'title': 'U',
  'release_date': '2024-05-24',
  'genres': ['Science Fiction'],
  'vote_average': 7.0,
  'overview': 'The storms we go through help us deconstruct to rebuild.'},
 {'id': 1655272,
  'title': 'U',
  'release_date': '2026-03-20',
  'genres': ['Music'],
  'vote_average': 0.0,
  'overview': "U is a album video that accompanies the American musician underscore's third album of the same name."},
 {'id': 39402,
  'title': 'Hercules Unchained',
  'release_date': '1959-02-14',
  'genres': ['Fantasy', 'Action'],
  'vote_average': 4.981,
  'overview': "En route to Thebes for an important diplomatic mission, Hercules drinks from a magic spring and loses his memory. He spends most of the movie in the pleasure gardens of Queen Omphale of Lydia. While young Ulysses tries to help him regain his memory, political tensions escalate in Thebes, and Hercules' new wife Iole finds herself in mortal danger."},
 {'id': 429,
  'title': 'The Good, the Bad and the Ugly',
  'release_date': '1966-12-23',
  'genres': ['Western'],
  'vote_average': 8.467,
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.'},
 {'id': 1510235,
  'title': 'Udaipur Files: Kanhaiya Lal Tailor Murder',
  'release_date': '2025-08-08',
  'genres': ['Crime', 'Drama'],
  'vote_average': 7.0,
  'overview': 'In June 2022, Kanhaiya Lal Sahu, a tailor in Udaipur, India, was brutally murdered. The events surrounding the murder are explored, delving into the conspiracy and the deeper issues of religious extremism, digital radicalization, and intelligence failures that led to the tragic event.'},
 {'id': 1284120,
  'title': 'The Ugly Stepsister',
  'release_date': '2025-03-07',
  'genres': ['Horror', 'Comedy', 'Drama'],
  'vote_average': 7.29,
  'overview': 'In a fairy-tale kingdom where beauty is a brutal business, Elvira battles to compete with her incredibly beautiful stepsister, and she will go to any length to catch the prince’s eye.'},
 {'id': 1132364,
  'title': 'U',
  'release_date': '2002-12-30',
  'genres': [],
  'vote_average': 8.4,
  'overview': 'A short movie by yuri A containing multiple poop facts.'},
 {'id': 1373799,
  'title': 'u',
  'release_date': '',
  'genres': [],
  'vote_average': 0.0,
  'overview': ''},
 {'id': 43194,
  'title': 'Ulysses',
  'release_date': '1954-10-06',
  'genres': ['Adventure', 'Fantasy'],
  'vote_average': 6.5,
  'overview': "A movie adaptation of Homer's second epic, that talks about Ulysses' efforts to return to his home after the end of ten years of war."},
 {'id': 146800,
  'title': 'Uma to onna to inu',
  'release_date': '1990-05-01',
  'genres': ['Drama', 'Horror'],
  'vote_average': 5.4,
  'overview': 'Three social outcasts who live near the seaside interact with each other in increasingly disturbing ways. The trio of characters are a woman who has killed her sister, a man who enjoys necrophilia, and a female amnesiac. The first woman engages in sadistic pursuits such as capturing young women at the beach to force them to engage in sexual activities, including copulation with a horse and a dog.'},
 {'id': 512563,
  'title': 'KochiKame the Movie 2: UFO Attack! The Great Tornado Strategy!!',
  'release_date': '2003-12-20',
  'genres': ['Animation', 'Action', 'Adventure', 'Comedy'],
  'vote_average': 7.0,
  'overview': "The movie starts off with Ryotsu (with Honda as his patsy) hatching another crackpot scam with a fake UFO sighting (via fake crop circles and a wire-hanging UFO). But the plan fails per usual, with the Kameari Park Police Box which results in Ohara punishes Ryotsu by subtracting him from the station's group vacation to Hawaii the following day."},
 {'id': 751490,
  'title': 'The Mole: Undercover in North Korea',
  'release_date': '2020-10-11',
  'genres': ['Documentary'],
  'vote_average': 7.1,
  'overview': "A real-life undercover thriller about two ordinary men who embark on an outrageously dangerous ten-year mission to penetrate the world's most secretive and brutal dictatorship: North Korea."},
 {'id': 991034,
  'title': 'U.',
  'release_date': '2022-07-17',
  'genres': [],
  'vote_average': 6.2,
  'overview': 'A girl remembers her past relationship.'},
 {'id': 362102,
  'title': 'The Laws of the Universe - Part 0',
  'release_date': '2015-09-26',
  'genres': ['Animation', 'Fantasy'],
  'vote_average': 10.0,
  'overview': 'Blackouts and other mysteries at NAZKA Academy hint at an impending alien invasion.'},
 {'id': 76745,
  'title': 'The Upper Hand',
  'release_date': '1966-03-02',
  'genres': ['Drama', 'Thriller', 'Crime'],
  'vote_average': 6.291,
  'overview': 'In Paris, a gold smuggler is at war with other local gangsters who want piece of the action. Then the mob shows up and makes things worse. And an undercover US Treasury Department agent is trying to infiltrate the smuggling business.'},
 {'id': 1013981,
  'title': 'Semi-document: Uwakizuma o nozoku',
  'release_date': '1979-01-06',
  'genres': [],
  'vote_average': 2.0,
  'overview': ''},
 {'id': 1273948,
  'title': 'Unspoken',
  'release_date': '2026-01-15',
  'genres': ['Crime', 'Drama', 'Action'],
  'vote_average': 0.0,
  'overview': 'A grieving Chinese father travels to America to collect his daughter and stays to catch the killer.'},
 {'id': 1071640,
  'title': 'Ultimate Revenge',
  'release_date': '2026-03-05',
  'genres': ['Action', 'Crime', 'Thriller'],
  'vote_average': 6.5,
  'overview': 'The Yau Tsim Mong area, the core commercial area of Hong Kong, has recently experienced a series of robberies. Many jewelry stores in the area have been ransacked by gangsters. Police unit is given the mission to take the gangsters into a custody, but the operation is not so easy.'},
 {'id': 1264805,
  'title': 'Once We Were Us',
  'release_date': '2025-12-31',
  'genres': ['Romance', 'Drama'],
  'vote_average': 7.292,
  'overview': 'Seoul, 2008. On a bus heading to their hometown, fate brings Eun-ho and Jeong-won together, sparking an unlikely friendship. While battling  a bustling and weary city life, they find themselves sharing lofty dreams and a love that comes to feel extraordinary. But, eventually, the harsh realities of life lead them to part ways. Over a decade after the separation, the two unexpectedly reunite on a flight back to Korea, where they reflect on their lost time.'},
 {'id': 10341,
  'title': 'Until the End of the World',
  'release_date': '1991-09-12',
  'genres': ['Drama', 'Science Fiction', 'Adventure'],
  'vote_average': 6.76,
  'overview': "In 1999, a woman's life is forever changed after she survives a car crash with two bank robbers, who enlist her help to take the money to a drop in Paris. On the way, she runs into another fugitive from the law — an American doctor on the run from the CIA. They want to confiscate his father's invention – a device which allows anyone to record their dreams and visions."},
 {'id': 286533,
  'title': 'Jakarta Undercover',
  'release_date': '2007-03-22',
  'genres': ['Thriller', 'Crime'],
  'vote_average': 7.0,
  'overview': 'After accidently killing her temperamental father in order to save her mom from his abuse, Viki flees from Medan to Jakarta with her autistic brother, Ara. To make ends meet in Jakarta, Viki poses as a transvestite and works as a striptease dancer. With no one to watch over her brother, Viki brings Ara every night to the club where she works and hide him in one corner of the room at the club. One day, Ara accidently witnesses an act of murder by Haryo, son of an official, and his friends. Realizing his crime action witness by Ara, Haryo and his friends chase Viki and Ara, determined to silene the two before they go to the police. For the sake of saving his brother’s life, Viki secretly flee from one place to another in order to escape Haryo and friends. Will Viki and Ara escape?'},
 {'id': 472640,
  'title': 'Under the Tree',
  'release_date': '2017-09-06',
  'genres': ['Drama', 'Comedy'],
  'vote_average': 6.655,
  'overview': "When Baldvin and Inga's next door neighbours complain that a tree in their backyard casts a shadow over their sundeck, what starts off as a typical spat between neighbours in the suburbs unexpectedly and violently spirals out of control."},
 {'id': 991034,
  'title': 'U.',
  'release_date': '2022-07-17',
  'genres': [],
  'vote_average': 6.2,
  'overview': 'A girl remembers her past relationship.'},
 {'id': 725027,
  'title': '℃-ute 2012 Spring-Summer ~Utsukushikutte Gomen ne~',
  'release_date': '2012-06-30',
  'genres': [],
  'vote_average': 0.0,
  'overview': 'Concert held at Nakano Sun Plaza.'},
 {'id': 85311,
  'title': 'UFO Robot Grendizer vs. Great Mazinger',
  'release_date': '1976-03-20',
  'genres': ['Animation', 'Action', 'Adventure', 'Science Fiction'],
  'vote_average': 5.8,
  'overview': "Alien invaders take over Great Mazinger who is at the entrance of a museum next to Mazinger Z as symbols of peace. Grendizer fights the evil invaders and Great Mazinger is recovered.  When the Vegan empire dispatches a new general to oversee the takeover of Earth, he quickly manages to capture Koji Kabuto and, learning of Great Mazinger through interrogation, quickly commandeers it from a museum where it was kept as a symbol of peace.  It is now up to Duke Fleed aboard Grendizer to stop humanity's former defender from becoming its destroyer."},
 {'id': 525586,
  'title': "Uzeyir's Life",
  'release_date': '1981-12-20',
  'genres': ['Music', 'Documentary', 'TV Movie'],
  'vote_average': 5.2,
  'overview': "The historical film about Azerbaijan composer Uzeyir Hadjibeyov's life."},
 {'id': 1611398,
  'title': 'Un hombre por semana',
  'release_date': '2026-01-08',
  'genres': ['Comedy', 'Romance', 'Drama'],
  'vote_average': 6.308,
  'overview': 'A divorced woman reconstructs her life and opens herself to love. Her search for dating apps takes her through fun and unpredictable moments to discover self-love.'},
 {'id': 52215,
  'title': 'Persons Unknown',
  'release_date': '1996-12-27',
  'genres': ['Thriller', 'Action'],
  'vote_average': 5.2,
  'overview': "When former cop and current security expert Jim Holland has a one night stand with Amanda after getting in her way roller-blading. That introduction turns out to be a well thought out plan by Amanda and her sister Molly, to obtain security codes. The girls and their cohorts rob his client and stash the loot. All the while, detective Jim has been following them and he grabs the money for himself. Then his conscience gets the best of him and he falls in love with Molly. His client turns out to be drug dealers and he's forced to risk his life to protect Molly and Amanda."},
 {'id': 142357,
  'title': 'Passion Unbounded',
  'release_date': '1995-04-07',
  'genres': ['Horror', 'Crime'],
  'vote_average': 2.0,
  'overview': 'An elder sister, after being abandoned in love, turns into a “black widow”-like serial killer.'},
 {'id': 725025,
  'title': "℃-ute 2011 Spring 'Chou! Chou Wonderful Tour'",
  'release_date': '2011-07-02',
  'genres': [],
  'vote_average': 0.0,
  'overview': 'Concert held at Yokosuka Geijutsu Theater.'},
 {'id': 725024,
  'title': "℃-ute 2010 Summer-Autumn ~Dance Special!! 'Chou Uranaito!!'~",
  'release_date': '2010-10-03',
  'genres': [],
  'vote_average': 0.0,
  'overview': 'Concert held at Nakano Sun Plaza.'},
 {'id': 224173,
  'title': '℃-ute 2013 Spring ~Treasure Box~',
  'release_date': '2013-06-29',
  'genres': ['Music'],
  'vote_average': 7.5,
  'overview': 'Concert held at Pacifico Yokohama National Convention Hall.'},
 {'id': 24527,
  'title': 'Undefeatable',
  'release_date': '1993-03-05',
  'genres': ['Action', 'Thriller'],
  'vote_average': 5.176,
  'overview': "The film follows Kristi Jones who, along with her gang, take part in Mafia-run street fights to earn money for her sister's college education. Kristi's sister hopes to become a doctor and pay for Kristi's education."},
 {'id': 1085678,
  'title': 'UFO Robot Grendizer Theatrical Version',
  'release_date': '1975-12-20',
  'genres': [],
  'vote_average': 7.0,
  'overview': 'Special episode in cinemascope format for Japanese cinemas.'},
 {'id': 156341,
  'title': 'Urban Snap-Shots',
  'release_date': '2008-02-29',
  'genres': ['Drama', 'Comedy'],
  'vote_average': 4.857,
  'overview': 'Comedic portrait of middle-aged women in Rio de Janeiro, including overworked housewife Magali and her over-the-top twin sister Magda, psychoanalyst Paula and her troublesome daughter Melanie, and stage star in crisis Lise.'},
 {'id': 725032,
  'title': '℃-ute 2014 Autumn ~Monster~',
  'release_date': '2014-11-11',
  'genres': [],
  'vote_average': 0.0,
  'overview': 'Concert held at Nippon Budokan.'},
 {'id': 394684,
  'title': 'May God Save Us',
  'release_date': '2016-10-28',
  'genres': ['Thriller', 'Crime', 'Drama'],
  'vote_average': 6.754,
  'overview': 'Madrid, summer 2011. Economic crisis. 15-M movement and 1.5 million pilgrims waiting for the Pope’s arrival live side by side in a Madrid that’s hotter and more chaotic than ever. In this context, detectives Velarde and Alfaro must find what seems to be a serial killer. Their against-the-clock hunt will make them realise something they’d never imagined: neither of them are so very different from the killer.'},
 {'id': 755812,
  'title': 'Miraculous World: New York, United HeroeZ',
  'release_date': '2020-09-25',
  'genres': ['Animation', 'Family', 'TV Movie', 'Action', 'Adventure'],
  'vote_average': 8.1,
  'overview': 'Marinette’s class is headed to New York, the city of superheroes, for French-American Friendship Week.'},
 {'id': 958234,
  'title': 'Unruly',
  'release_date': '2023-03-09',
  'genres': ['Drama'],
  'vote_average': 6.6,
  'overview': "The year is 1933, and society has certain expectations of how young women should behave. 17-year-old Maren is wild and unruly and is in turn sent to the women's institution at Sprogø to become more compliant. The stay at Sprogø has the opposite effect on Maren, and she ignites a spark in Sørine, who after six years at the institution has become accustomed to the norms of the time and the expectations of the institution. Slowly the two begin to form an unbreakable bond, which will affect the rest of their lives."},
 {'id': 1078920,
  'title': 'Unicorns',
  'release_date': '2023-05-19',
  'genres': ['Drama'],
  'vote_average': 4.667,
  'overview': 'Isa is a feminist, bisexual, and polyamorous posh girl, she passionately defends her life. When Guillem proposes to be a monogamous couple, Isa is not sure if he wants to change her life and, given her lack of decision, Guillem decides to break the relationship. Living in a world of appearances and comforts, her contradictions come to light and her universe is crumbling at the blow of likes and moral judgments in this web that social networks have become.'},
 {'id': 482677,
  'title': 'Upload',
  'release_date': '2015-12-02',
  'genres': ['Drama'],
  'vote_average': 3.7,
  'overview': 'When an amateur sexting video makes the rounds on social media, several involved individuals have to face the consequences. A film that takes on the subject of sexting and cyberbullying.'},
 {'id': 645105,
  'title': 'Ciao UFO',
  'release_date': '2025-12-25',
  'genres': ['Drama'],
  'vote_average': 8.0,
  'overview': 'Wah Fu Estate in Aberdeen is the home of many urban legends, but few were as outlandish as the one that happened in the 1980s: One night, residents turned their heads to the sky and saw a giant UFO hovering above them for five minutes. No one else could prove or explain the odd phenomenon, but it becomes the pivotal event for three young people in this long-awaited return to form for director Patrick Leung (La Brassiere, Simply Actors). This charming sci-fi comedy also marks the reunion of Tsui Tien-you, Wong Younam and Charlene Choi, who co-starred in 2002 teen comedy hit Summer Breeze of Love.'},
 {'id': 19738,
  'title': 'Revolutionary Girl Utena: The Movie',
  'release_date': '1999-08-14',
  'genres': ['Animation', 'Drama', 'Fantasy', 'Romance'],
  'vote_average': 7.4,
  'overview': 'In a loose retelling of the Revolutionary Girl Utena TV series, Utena Tenjou arrives at Ohtori Academy, only to be immediately swept up in a series of duels for the hand of her classmate Anthy Himemiya and the power she supposedly holds. At the same time, Utena reunites with Touga Kiryuu, a friend from her childhood who seems to know the secrets behind the duels. Utena must discover those secrets for herself, before the power that rules Ohtori claims her and her friends, new and old.'},
 {'id': 83041,
  'title': 'The Ultimate Winner',
  'release_date': '2011-04-14',
  'genres': ['Drama'],
  'vote_average': 7.5,
  'overview': "Since young, Shi Tian Cai (Li Nanxing) was known among his peers to be the junior gambling king thanks to his gambling addict of a father. Years later, Tian Cai gets married to Zhi Hui who is about to give birth. All this while Tian Cai have been supporting his family through gambling, but with a kid now on board, things just got tougher. Without hesitation Tian Cai dabbles with the high-stake circles and with his talent and reputation manages to make a huge windfall. Tian Cai's much sought after talent in the gambling circle generates envy from Taiwanese tycoon Li Guan Jun, and each step that Tian Cai takes brings him closer to his nemesis."},
 {'id': 589705,
  'title': 'Udgharsha',
  'release_date': '2019-03-22',
  'genres': ['Thriller'],
  'vote_average': 1.0,
  'overview': 'A thriller film directed by Sunil Kumar Desai, starring Sai Dhanshika, Tanya Hope and Thakur Anoop Singh in the lead roles.'},
 {'id': 70774,
  'title': 'Walt Disney: Once Upon a Time',
  'release_date': '2006-09-15',
  'genres': ['Documentary'],
  'vote_average': 7.6,
  'overview': "Talks about the iconographical sources that Walt Disney and his studio's designers drew on to create the films that are incontestably among the masterpieces of animation."},
 {'id': 1185339,
  'title': 'Farscape Undressed',
  'release_date': '2001-03-16',
  'genres': ['Documentary'],
  'vote_average': 7.0,
  'overview': "A one hour documentary/primer aired to prepare new viewers of the Sci-Fi Channel's Farscape for the third season. It includes clips from the first two seasons and explanations on each of the main characters."},
 {'id': 685819,

In [ ]:
# Limpiamos lista para quedarnos solamente con las que comiencen por 'U'
pelis_limpio = limpiar_lista_pelis(lista_pelis,mi_inicial)

In [5]:
# Comprobamos cuántos registros hay
len(pelis_limpio)

NameError: name 'pelis_limpio' is not defined

In [ ]:
# Visualizamos algunos datos
pelis_limpio

[{'id': 39405,
  'title': 'U',
  'release_date': '2006-10-11',
  'genres': ['Animation', 'Fantasy'],
  'vote_average': 6.6,
  'overview': "Since her parents passed away, Princess Mona lives by herself in a castle with two hideous, ghastly characters, Goomi and His Lordship. One day her sobs draw the attention of a unicorn, called U, who wants to comfort and protect Mona for as long as she needs. U becomes Mona's companion, her confidant and her inseparable friend. While Mona grows into a beautiful princess, a group of charming, peaceful and fanciful Yeah-Yeah’s settles in the neighboring forest. They have no particular special powers, yet they soon bring about major changes in everyone's lives, especially in Kulka, the dreamy musician."},
 {'id': 1303795,
  'title': 'U',
  'release_date': '2024-05-24',
  'genres': ['Science Fiction'],
  'vote_average': 7.0,
  'overview': 'The storms we go through help us deconstruct to rebuild.'},
 {'id': 1655272,
  'title': 'U',
  'release_date': '2026-03-20',
  'genres': ['Music'],
  'vote_average': 0.0,
  'overview': "U is a album video that accompanies the American musician underscore's third album of the same name."},
 {'id': 1510235,
  'title': 'Udaipur Files: Kanhaiya Lal Tailor Murder',
  'release_date': '2025-08-08',
  'genres': ['Crime', 'Drama'],
  'vote_average': 7.0,
  'overview': 'In June 2022, Kanhaiya Lal Sahu, a tailor in Udaipur, India, was brutally murdered. The events surrounding the murder are explored, delving into the conspiracy and the deeper issues of religious extremism, digital radicalization, and intelligence failures that led to the tragic event.'},
 {'id': 1132364,
  'title': 'U',
  'release_date': '2002-12-30',
  'genres': [],
  'vote_average': 8.4,
  'overview': 'A short movie by yuri A containing multiple poop facts.'},
 {'id': 1373799,
  'title': 'u',
  'release_date': '',
  'genres': [],
  'vote_average': 0.0,
  'overview': ''},
 {'id': 43194,
  'title': 'Ulysses',
  'release_date': '1954-10-06',
  'genres': ['Adventure', 'Fantasy'],
  'vote_average': 6.5,
  'overview': "A movie adaptation of Homer's second epic, that talks about Ulysses' efforts to return to his home after the end of ten years of war."},
 {'id': 146800,
  'title': 'Uma to onna to inu',
  'release_date': '1990-05-01',
  'genres': ['Drama', 'Horror'],
  'vote_average': 5.4,
  'overview': 'Three social outcasts who live near the seaside interact with each other in increasingly disturbing ways. The trio of characters are a woman who has killed her sister, a man who enjoys necrophilia, and a female amnesiac. The first woman engages in sadistic pursuits such as capturing young women at the beach to force them to engage in sexual activities, including copulation with a horse and a dog.'},
 {'id': 991034,
  'title': 'U.',
  'release_date': '2022-07-17',
  'genres': [],
  'vote_average': 6.2,
  'overview': 'A girl remembers her past relationship.'},
 {'id': 1273948,
  'title': 'Unspoken',
  'release_date': '2026-01-15',
  'genres': ['Crime', 'Drama', 'Action'],
  'vote_average': 0.0,
  'overview': 'A grieving Chinese father travels to America to collect his daughter and stays to catch the killer.'},
 {'id': 1071640,
  'title': 'Ultimate Revenge',
  'release_date': '2026-03-05',
  'genres': ['Action', 'Crime', 'Thriller'],
  'vote_average': 6.5,
  'overview': 'The Yau Tsim Mong area, the core commercial area of Hong Kong, has recently experienced a series of robberies. Many jewelry stores in the area have been ransacked by gangsters. Police unit is given the mission to take the gangsters into a custody, but the operation is not so easy.'},
 {'id': 10341,
  'title': 'Until the End of the World',
  'release_date': '1991-09-12',
  'genres': ['Drama', 'Science Fiction', 'Adventure'],
  'vote_average': 6.76,
  'overview': "In 1999, a woman's life is forever changed after she survives a car crash with two bank robbers, who enlist her help to take the money to a drop in Paris. On the way, she runs into another fugitive from the law — an American doctor on the run from the CIA. They want to confiscate his father's invention – a device which allows anyone to record their dreams and visions."},
 {'id': 472640,
  'title': 'Under the Tree',
  'release_date': '2017-09-06',
  'genres': ['Drama', 'Comedy'],
  'vote_average': 6.655,
  'overview': "When Baldvin and Inga's next door neighbours complain that a tree in their backyard casts a shadow over their sundeck, what starts off as a typical spat between neighbours in the suburbs unexpectedly and violently spirals out of control."},
 {'id': 991034,
  'title': 'U.',
  'release_date': '2022-07-17',
  'genres': [],
  'vote_average': 6.2,
  'overview': 'A girl remembers her past relationship.'},
 {'id': 85311,
  'title': 'UFO Robot Grendizer vs. Great Mazinger',
  'release_date': '1976-03-20',
  'genres': ['Animation', 'Action', 'Adventure', 'Science Fiction'],
  'vote_average': 5.8,
  'overview': "Alien invaders take over Great Mazinger who is at the entrance of a museum next to Mazinger Z as symbols of peace. Grendizer fights the evil invaders and Great Mazinger is recovered.  When the Vegan empire dispatches a new general to oversee the takeover of Earth, he quickly manages to capture Koji Kabuto and, learning of Great Mazinger through interrogation, quickly commandeers it from a museum where it was kept as a symbol of peace.  It is now up to Duke Fleed aboard Grendizer to stop humanity's former defender from becoming its destroyer."},
 {'id': 525586,
  'title': "Uzeyir's Life",
  'release_date': '1981-12-20',
  'genres': ['Music', 'Documentary', 'TV Movie'],
  'vote_average': 5.2,
  'overview': "The historical film about Azerbaijan composer Uzeyir Hadjibeyov's life."},
 {'id': 1611398,
  'title': 'Un hombre por semana',
  'release_date': '2026-01-08',
  'genres': ['Comedy', 'Romance', 'Drama'],
  'vote_average': 6.308,
  'overview': 'A divorced woman reconstructs her life and opens herself to love. Her search for dating apps takes her through fun and unpredictable moments to discover self-love.'},
 {'id': 24527,
  'title': 'Undefeatable',
  'release_date': '1993-03-05',
  'genres': ['Action', 'Thriller'],
  'vote_average': 5.176,
  'overview': "The film follows Kristi Jones who, along with her gang, take part in Mafia-run street fights to earn money for her sister's college education. Kristi's sister hopes to become a doctor and pay for Kristi's education."},
 {'id': 1085678,
  'title': 'UFO Robot Grendizer Theatrical Version',
  'release_date': '1975-12-20',
  'genres': [],
  'vote_average': 7.0,
  'overview': 'Special episode in cinemascope format for Japanese cinemas.'},
 {'id': 156341,
  'title': 'Urban Snap-Shots',
  'release_date': '2008-02-29',
  'genres': ['Drama', 'Comedy'],
  'vote_average': 4.857,
  'overview': 'Comedic portrait of middle-aged women in Rio de Janeiro, including overworked housewife Magali and her over-the-top twin sister Magda, psychoanalyst Paula and her troublesome daughter Melanie, and stage star in crisis Lise.'},
 {'id': 958234,
  'title': 'Unruly',
  'release_date': '2023-03-09',
  'genres': ['Drama'],
  'vote_average': 6.6,
  'overview': "The year is 1933, and society has certain expectations of how young women should behave. 17-year-old Maren is wild and unruly and is in turn sent to the women's institution at Sprogø to become more compliant. The stay at Sprogø has the opposite effect on Maren, and she ignites a spark in Sørine, who after six years at the institution has become accustomed to the norms of the time and the expectations of the institution. Slowly the two begin to form an unbreakable bond, which will affect the rest of their lives."},
 {'id': 1078920,
  'title': 'Unicorns',
  'release_date': '2023-05-19',
  'genres': ['Drama'],
  'vote_average': 4.667,
  'overview': 'Isa is a feminist, bisexual, and polyamorous posh girl, she passionately defends her life. When Guillem proposes to be a monogamous couple, Isa is not sure if he wants to change her life and, given her lack of decision, Guillem decides to break the relationship. Living in a world of appearances and comforts, her contradictions come to light and her universe is crumbling at the blow of likes and moral judgments in this web that social networks have become.'},
 {'id': 482677,
  'title': 'Upload',
  'release_date': '2015-12-02',
  'genres': ['Drama'],
  'vote_average': 3.7,
  'overview': 'When an amateur sexting video makes the rounds on social media, several involved individuals have to face the consequences. A film that takes on the subject of sexting and cyberbullying.'},
 {'id': 589705,
  'title': 'Udgharsha',
  'release_date': '2019-03-22',
  'genres': ['Thriller'],
  'vote_average': 1.0,
  'overview': 'A thriller film directed by Sunil Kumar Desai, starring Sai Dhanshika, Tanya Hope and Thakur Anoop Singh in the lead roles.'},
 {'id': 576784,
  'title': 'Upon the Magic Roads',
  'release_date': '2021-02-18',
  'genres': ['Adventure', 'Fantasy'],
  'vote_average': 6.8,
  'overview': 'Romantic John the Fool and his friend Foal set out on a series of unpredictable adventures in different magical worlds. The two buddies will have to outsmart an evil tyrant king, catch the firebird, and find John’s true love.'},
 {'id': 1305715,
  'title': 'Unexpected Family',
  'release_date': '2026-01-01',
  'genres': ['Comedy', 'Drama'],
  'vote_average': 6.667,
  'overview': "When an aging local starts to lose his memory, those around him decide to recreate an important family moment in his life for him to relive. What they discover isn't what they expect — about both themselves and about the mysterious man's past."},
 {'id': 537653,
  'title': 'Ubasute',
  'release_date': '2014-12-29',
  'genres': [],
  'vote_average': 0.0,
  'overview': 'The "yutori" generation of Japan is accused of being one of the laziest in society. Being raised in a pressure-free education system, the "yutori" are often criticized for poor results and lack of drive in the workplace. Touma (Kensuke Owada), at age 27, struggles to keep a job, sleeps at an internet cafe, and complains about his every day with online friends. They blame society, and Touma, full of pride yet lost without a purpose, is about to drop out of it.  Frustrated with the elder generations telling him what to do, he wishes all old people were sent away, like the folklore "UBASUTE" where they are abandoned on a mountain. He finds an intriguing blog on the topic, and messages the blogger, a positive woman claiming to be his age. Little does he know, his new friend is actually a 72 year-old woman. Touma slowly learns how to face himself and improve his lifestyle thanks to their online conversations, and they finally get a chance to meet...'},
 {'id': 1027672,
  'title': 'Universal Prayer',
  'release_date': '2015-03-20',
  'genres': ['Drama', 'Music', 'Family'],
  'vote_average': 0.0,
  'overview': 'We seek to find the inner light of each one and thus turn on new lights, to leave the paths illuminated, so as not to walk blindly and alone. It is having a real awareness of our actions, that our life is a commitment and that if each one of us acts, a great change will be seen in the world. The power of life is to give us existence.'},
 {'id': 1223178,
  'title': 'Umamusume: Pretty Derby - Beginning of a New Era',
  'release_date': '2024-05-24',
  'genres': ['Animation', 'Drama', 'Comedy', 'Fantasy'],
  'vote_average': 7.9,
  'overview': 'Jungle Pocket, an Umamusume who has been racing tirelessly in pursuit of becoming the greatest, is ready to take on the once-in-a-lifetime Classic Triple Crown series. However, standing in her way are rivals from the same generation, whose talent may even surpass her own.'},
 {'id': 1340355,
  'title': 'Under Ninja',
  'release_date': '2025-01-24',
  'genres': ['Action'],
  'vote_average': 7.0,
  'overview': 'The once-proud Japanese Ninja disappeared after the war when GHQ disbanded their organization.However, in reality ninjas still exist secretly and it is said that there are 200 thousand of them.And some elite ninjas are secretly operating behind the scenes in national-level struggles.On the other hand, grassroots ninjas often cannot find jobs, and one of them, Yun Yin Jiu Lang, also lives a life similar to that of the NEET generation.However, there is finally a major "endurance" around Ninomaru!'},
 {'id': 366514,
  'title': 'Up for Love',
  'release_date': '2016-05-04',
  'genres': ['Comedy', 'Romance', 'Drama'],
  'vote_average': 6.013,
  'overview': 'Diane is a well-known lawyer, divorced for three years. She loses her mobile telephone and receives a call from the person who finds it. That person is Alexandre, a charming man and the perfect gentleman. They make a connection over the phone and agree to meet up the following day. But when Alexandre arrives, there\'s a surprise in store when Diane discovers he is only 4\' 6" tall. From that moment on, Diane tries to overcome the prejudices of society and her own fears to experience the best time of her life...'},
 {'id': 791370,
  'title': 'Unwanted Cinema',
  'release_date': '2005-01-01',
  'genres': ['Documentary'],
  'vote_average': 0.0,
  'overview': 'The documentary shows the exclusion of Jewish film makers after Hitler took power in Germany and how this led to an independent filmproduction in Vienna and Budapest from 1934 till 1937. With previously unpublished archive material are portrayed: Hermann Kosterlitz (Henry Koster), Felix Joachimson (Jackson), Joe Pasternak, Otto Wallburg, Hans Jaray, Franziska Gaal, Rosy Barsony, Hortense Raky, Oskar Pilzer, Zoltan Vidor, Ernst Verebes.'},
 {'id': 305896,
  'title': 'Ursa Minor Blue',
  'release_date': '1993-05-21',
  'genres': ['Animation', 'Fantasy', 'Adventure'],
  'vote_average': 6.8,
  'overview': 'This adventurous story of a boy named Uri and an old man takes place in the cosmic Milky Way where the starfish live. This is the tale of their fantasy journey in search of the mysterious monster fish.'},
 {'id': 1001311,
  'title': 'Under Paris',
  'release_date': '2024-06-04',
  'genres': ['Action', 'Horror'],
  'vote_average': 5.918,
  'overview': 'In order to save Paris from an international bloodbath, a grieving scientist is forced to face her tragic past when a giant shark appears in the Seine.'},
 {'id': 274056,
  'title': 'Up&Down',
  'release_date': '2012-08-21',
  'genres': ['Romance', 'Comedy'],
  'vote_average': 4.3,
  'overview': 'A struggling actor pushing 30 works a day job at a luxury hotel, shepherding guests and party goers, while yearning for the girl of his dreams.'},
 {'id': 868668,
  'title': 'Ustaad Bhagat Singh',
  'release_date': '2026-03-18',
  'genres': ['Action', 'Comedy', 'Drama'],
  'vote_average': 6.2,
  'overview': "A tribal boy is shaped by the values of his teacher, who gives him the name 'Bhagat Singh'. He grows up deeply rooted in strong morals, which guide his actions throughout his life.He stands firm against injustice and takes on powerful evil forces, even when facing overwhelming odds."},
 {'id': 53141,
  'title': 'Undercurrent',
  'release_date': '1999-01-01',
  'genres': ['Action', 'Thriller', 'Romance'],
  'vote_average': 3.5,
  'overview': "A nightclub manager with financial problems accepts an offer to seduce another man's wife for money, and soon finds himself entwined in a web of double-crossing con artists."},
 {'id': 1027509,
  'title': 'Uno Koichiro no Hotel Maid Nikki',
  'release_date': '1980-03-15',
  'genres': [],
  'vote_average': 2.0,
  'overview': ''},
 {'id': 582666,
  'title': 'Utano Princesama Maji LOVE Kingdom',
  'release_date': '2019-06-14',
  'genres': ['Animation', 'Romance', 'Music'],
  'vote_average': 6.25,
  'overview': "What's better than a concert by one of your favorite singing groups? A concert by three of your favorite singing groups, of course! That's what lucky fans get when three of the most popular vocal groups from the UTANO★PRINCESAMA franchise all come together for a single epic motion picture performance. Have you got your tickets yet? If you have, come join ST★RISH, QUARTET NIGHT, and HE★VENS as they all take to the stage! It's an epic battle of the bands where there's no battle and everyone wins in Utano★Princesama Maji Love Kingdom!"},
 {'id': 1027867,
  'title': 'U Motherbaker - The Movie',
  'release_date': '2023-01-13',
  'genres': ['Drama', 'Comedy'],
  'vote_average': 3.5,
  'overview': 'A film sequel to the popular series, U Motherbaker. It is a Taiwanese family comedy about culture and the challenges of transforming a traditional cake shop. The film spin-off depicts the mother’s adventures of being the number one fan of the superstar OO.'},
 {'id': 257673,
  'title': 'Uku Ukai',
  'release_date': '2006-11-24',
  'genres': ['Documentary'],
  'vote_average': 6.2,
  'overview': 'Sorrow does not come merely from contemplating death, which forces us to look into Eternity, but also from life, which compels us to confront Time", wrote Russian philosopher Nikolai Berdyayev. Renowned Lithuanian documentarist Audrius Stonys took these words as a motto for his latest film, a meditative visual essay which portrays old people undertaking all kinds of activities, meditation and group laughter therapy. Without a single word of commentary, he creates from sophisticated, aesthetic images a compelling study of human corporeality which, in an ideal union with spiritual equilibrium, can sustain us with the pledge that old age doesn\'t have to be a painful wait for the last breath.'},
 {'id': 1446584,
  'title': 'Unification of Japan 65',
  'release_date': '2024-11-25',
  'genres': ['Action', 'Crime', 'Drama'],
  'vote_average': 0.0,
  'overview': 'The incident occurred without any warning. A member of the Kyowakai was shot in Kyoto. This shooting incident, which took place in Kansai—the very region Kyowakai was supposed to have unified—sent shockwaves through Himuro (Yasukaze Motomiya) and his men.  As Himuro and Tamura (Yoshiyuki Yamaguchi) hurriedly prepared for an emergency executive meeting in Kobe, they were stopped by Kuroiwa (Susumu Terajima ) from the Hachiwari Police Department, who came to visit the Himuro-gumi. According to Kuroiwa, Matsumiya (Hongo Gen) from the special investigation unit believed that this incident was an internal conflict within the Kyowakai.  Himuro and Tamura learned that the reason for this suspicion was a clash between Hayashida (Shu Ehara) and Kamiyama (Naoki Yamazaki) over a land redevelopment project in Kyoto. Determined to get to the bottom of the matter, they set out for Kyoto. In that area, various people’s emotions and interests were intricately intertwined…'},
 {'id': 484724,
  'title': 'Uros the Stupid',
  'release_date': '1989-01-01',
  'genres': ['Family', 'Comedy'],
  'vote_average': 0.0,
  'overview': "The Zivkovic family lives on a hilly village, on cleared part of land. Having many relatives, their lives are interlaced, and jobs distributed. Their biggest problem is a family that lives on the village edge and whose members steal, and Uros the Stupid, single and infantile Markovic family member. Contrary to the world of elders, Urosh and children lead their life of some kind. Suddenly, postman brings the telegram saying that some forgotten cousin from America has died and left two million dollars of inheritance. Unrest enters life of peasants. Everyone has some idea on how to invest the money, feeling at the same time that they don't need it. All of their actions will end differently from what they expected."},
 {'id': 14160,
  'title': 'Up',
  'release_date': '2009-05-28',
  'genres': ['Animation', 'Comedy', 'Family', 'Adventure'],
  'vote_average': 7.959,
  'overview': 'Carl Fredricksen spent his entire life dreaming of exploring the globe and experiencing life to its fullest. But at age 78, life seems to have passed him by, until a twist of fate (and a persistent 8-year old Wilderness Explorer named Russell) gives him a new lease on life.'},
 {'id': 511358,

In [64]:
# Convertimos a df
df_pelis = lista2df(pelis_limpio)
df_pelis

,id,title,release_date,genres,vote_average,overview
0,39405,U,2006-10-11,"[Animation, Fantasy]",6.6,"Since her parents passed away, Princess Mona l..."
1,1303795,U,2024-05-24,[Science Fiction],7.0,The storms we go through help us deconstruct t...
2,1655272,U,2026-03-20,[Music],0.0,U is a album video that accompanies the Americ...
3,1510235,Udaipur Files: Kanhaiya Lal Tailor Murder,2025-08-08,"[Crime, Drama]",7.0,"In June 2022, Kanhaiya Lal Sahu, a tailor in U..."
4,1132364,U,2002-12-30,[],8.4,A short movie by yuri A containing multiple po...
...,...,...,...,...,...,...
3454,1418551,Unbearably Loud,2024-04-17,[Documentary],0.0,This film tells the stories of five Russian fa...
3455,1297660,Us and Our Elders,1952-01-01,[Documentary],0.0,Instructive pictures that show how to try to s...
3456,349343,Ulysses,1999-01-09,[],0.0,
3457,991932,Uh-puh!,2022-07-08,[],0.0,"Danbi, who was notified of her breakup by her ..."
3458,562911,Unidentified,2017-12-01,[Animation],0.0,

In [ ]:
# Exportamos el df a un .csv con el nombre 'peliculas_u.csv'
export_csv(df_pelis,'peliculas_u')

In [ ]:
# Leemos el .csv para comprobar que el archivo está bien creado
pd.read_csv("data/peliculas_u.csv")

,id,title,release_date,genres,vote_average,overview
0,39405,U,2006-10-11,"['Animation', 'Fantasy']",6.6,"Since her parents passed away, Princess Mona l..."
1,1303795,U,2024-05-24,['Science Fiction'],7.0,The storms we go through help us deconstruct t...
2,1655272,U,2026-03-20,['Music'],0.0,U is a album video that accompanies the Americ...
3,1510235,Udaipur Files: Kanhaiya Lal Tailor Murder,2025-08-08,"['Crime', 'Drama']",7.0,"In June 2022, Kanhaiya Lal Sahu, a tailor in U..."
4,1132364,U,2002-12-30,[],8.4,A short movie by yuri A containing multiple po...
...,...,...,...,...,...,...
3454,1418551,Unbearably Loud,2024-04-17,['Documentary'],0.0,This film tells the stories of five Russian fa...
3455,1297660,Us and Our Elders,1952-01-01,['Documentary'],0.0,Instructive pictures that show how to try to s...
3456,349343,Ulysses,1999-01-09,[],0.0,NaN
3457,991932,Uh-puh!,2022-07-08,[],0.0,"Danbi, who was notified of her breakup by her ..."
3458,562911,Unidentified,2017-12-01,['Animation'],0.0,NaN