![imagen](./img/python.jpg)

# Lectura Escritura

En este módulo vas a ver diferentes maneras de leer y escribir datos desde archivos locales. Rara vez trabajarás únicamente con los datos que genere tu programa de Python, sino que lo normal será acudir a una fuente de datos, o leer de algún archivo.

1. [Archivos](#1.-Archivos)
2. [Abrir ficheros](#2.-Abrir-ficheros)
3. [CSV](#3.-CSV)
4. [Excel](#4.-Excel)
5. [JSON](#5.-JSON)
6. [TXT](#6.-TXT)
7. [ZIP](#7.-ZIP)
8. [pickle](#8.-pickle)
9. [Encoding](#9.-Encoding)
10. [Archivos y carpetas](#10.-Archivos-y-carpetas)

## 1. Archivos
Antes de ir a leer o escribir archivos, es importante saber exáctamente qué es un archivo. **Un archivo es un conjunto de datos almacenados en el ordenador en forma de bits.** Los datos se organizan en un formato específico, pudiendo ser un archivo de texto, un ejecutable... pero en el fondo todos esos archivos se traducen a nivel binario para el procesado del ordenador. Los archivos se componen de:

1. **Header**: metadatos del archivo (nombre, tamaño, tipo...)
2. **Data**: contenido del archivo
3. **End of file (EOF)**: caracter especial que indica el final del archivo.

![imagen](./img/file.png)

#### File path
Hay tres elementos que tenemos que conocer cuando leamos un archivo:
1. **Folder path**: en que lugar del ordenador está el archivo. Y no solo eso, si no en qué directorio está apuntando el programa de Python.
2. **File name**
3. **Extension**: lo que va después del punto

Fíjate en la siguiente imagen:

![imagen](./img/path.png)

* Si estamos trabajando en el directorio *to*, accederemos a *cats.gif* como `cats.gif`
* Si queremos leer *dog_breeds.txt*, hay que ir un directorio hacia atrás, `../dog_breeds.txt`
* Y si queremos acceder a `animals.csv`, son dos directorios hacia atrás: `../../animals.csv`

Siempre podemos poner la ruta absoluta (`C/Users/usuario/Archivos/Bootcamp/Python/animals.csv`) para el acceso a cada archivo, **aunque no es lo recomendable**.

[Buena guía para iniciarse en la lectura/escritura de archivos con Python.](https://realpython.com/read-write-files-python/)

## 2. Abrir ficheros
A lo largo de este notebook verás diferentes funciones para leer archivos, en función de la extensión cada uno. Estas funciones provienen de otras librerías y nos facilitan mucho la vida a la hora de leer o escribir archivos. No obstante, Python tiene sus propias funciones *built-in*, con las que no es necesario utilizar otros paquetes. 

Para ello **usaremos la función `open`**, que devuelve un objeto de tipo `File`, con unos métodos y atributos propios empleados para obtener información de los archivos abiertos. `open` sigue la siguiente sitaxis:

```Python
file_object  = open("filename", "mode")
```

El primer argumento es el nombre del archivo, mientras que en el modo tendremos que especificar si queremos leer, o escribir. Por defecto leerá, es decir, el parámetro valdrá *r*, de read. [Te dejo el enlace a la documentación para consultar el resto de modos](https://docs.python.org/3/library/functions.html#open).

Vamos a probar a leer un archivo. La siguiente sintaxis de línea se utiliza porque en algún momento se tiene que cerrar el archivo. Se abre, leemos, realizamos operaciones, y cuando acaba el `with open()`, se cierra el archivo. **Leer y escribir mientras los archivos están abiertos nos dará errores**.

In [1]:
import os
os.getcwd()

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría'

In [2]:
with open('./data/dog_breeds.txt', 'r') as open_file:
    all_text = open_file.read()
    print(type(all_text))
    print(all_text)

<class 'str'>
Pug
Jack Russell Terrier
English Springer Spaniel
German Shepherd
Staffordshire Bull Terrier
Cavalier King Charles Spaniel
Golden Retriever
West Highland White Terrier
Boxer
Border Terrier

El método `.read()` nos devuelve un string con todo el texto, que no es lo ideal para tratar luego los datos.

En el siguiente ejemplo vemos como también lo leemos, pero en este caso cada línea la guarda en una lista.

In [3]:
with open('data/dog_breeds.txt', 'r') as open_file:
    all_text = open_file.readlines()
    print(type(all_text))
    print(all_text)

<class 'list'>
['Pug\n', 'Jack Russell Terrier\n', 'English Springer Spaniel\n', 'German Shepherd\n', 'Staffordshire Bull Terrier\n', 'Cavalier King Charles Spaniel\n', 'Golden Retriever\n', 'West Highland White Terrier\n', 'Boxer\n', 'Border Terrier']

In [4]:
import pprint
pprint.pprint(all_text)

['Pug\n',
 'Jack Russell Terrier\n',
 'English Springer Spaniel\n',
 'German Shepherd\n',
 'Staffordshire Bull Terrier\n',
 'Cavalier King Charles Spaniel\n',
 'Golden Retriever\n',
 'West Highland White Terrier\n',
 'Boxer\n',
 'Border Terrier']

In [5]:
with open('data/dog_breeds.txt', 'r') as open_file:
    for line in open_file.readlines():
        print(line, end = '')
  
print('Fin')

Pug
Jack Russell Terrier
English Springer Spaniel
German Shepherd
Staffordshire Bull Terrier
Cavalier King Charles Spaniel
Golden Retriever
West Highland White Terrier
Boxer
Border TerrierFin

In [6]:
with open('data/dog_breeds.txt', 'r') as reader:
    # Read and print the entire file line by line
    for line in reader:
        print(line, end='')

Pug
Jack Russell Terrier
English Springer Spaniel
German Shepherd
Staffordshire Bull Terrier
Cavalier King Charles Spaniel
Golden Retriever
West Highland White Terrier
Boxer
Border Terrier

Si queremos escribir

In [7]:
with open('data/preguntas.py', 'w') as new_file:
    new_file.write("print(\"Hola mundo\")\n")
    new_file.write("#Esto se crea?\n")
    new_file.write("#Segunda linea\n")
    new_file.write("#Tercera linea\n")
    print("Ya se ha escrito")

Ya se ha escrito

In [8]:
with open("data/preguntas.py", "r") as new_file:
    linea = new_file.readline()
    print(linea)
    print(new_file.readline())
    print(new_file.readline())

print("Hola mundo")

#Esto se crea?

#Segunda linea

Opción "w" para escribir. Si no existe el archivo lo crea. Si existe se destruye su contenido.

In [9]:
with open('data/class_hlf.py', 'w') as new_file:
    new_file.write("class Barco():\n")
    new_file.write("\tamarre = 'Barcelona'\n")
    new_file.write("\teslora = 4")
    # new_file.write("Pregunta")
    print("Ya se ha escrito")

Ya se ha escrito

In [10]:
with open('data/class_hlf.py', 'w') as new_file:
    new_file.write("class Barco():\n")
    new_file.write("\tamarre = 'Bilbao'\n")
    new_file.write("\teslora = 10")
    # new_file.write("Pregunta")
    print("Ya se ha escrito")

Ya se ha escrito

Opción "a" para añadir, append. Si no existe lo crea. No destruye el contenido si ya existe. Agrega.

In [11]:
with open('data/class_hlf.py', 'a') as new_file:
    new_file.write("\n\nclass Tablero():\n")
    new_file.write("\tjugadores = 4")
    # new_file.write("Pregunta")
    print("Ya se ha escrito")

Ya se ha escrito

## 3. CSV
***Comma Separated Values*. Es el estándar de la industria que se utiliza para leer/escribir datos en formato tabla**, en dos dimensiones. Se llaman *Comma Separated Values* ya que todos los valores de las columnas van separados por comas, y las filas por saltos de línea. **Su extension de archivo es `.csv`**. Además, el 99% de las veces llevan la cabecera de columnas en la primera línea. Aunque no siempre se dará el caso, depende de la manera en la que se haya generado el CSV.

**Es el archivo más común utilizado para guardar datos tabulares, puesto que ocupa muy poco espacio** ya que es simplemente un archivo de texto plano, con todos los datos separados por el caracter coma. Y además, sencillo de entender, los datos no van en un árbol json o xml... Si lo abrimos como texto plano, son los datos separados por coma, tal cual. 

Por supuesto, tenemos el otro gran protagonista en cuanto a almacenamiento de datos en formato tabla, **el Excel**. A ver, son cosas diferentes. El Excel tiene sus formatos (.xlsx, .xls), que encima son muy eficientes ya que el dato va comprimido, pero no deja de ser un software de pago para tratar los datos, mientras que **el CSV es un formato estándar que se utiliza en todos los sistemas operativos para el exportado/importado de datos**.

Como decíamos al principio, los CSVs se llaman *Comma Separated Values* porque todos los valores van separados por comas... bueno, esto no es del todo cierto ya que **puede haber otro caracter que no sea la coma**, como por ejemplo el punto y coma. ¿Por qué? Simplemente porque si tenemos datos decimales, separados por comas, no vamos a saber distinguir cuando una coma es de un decimal, o es el separador de columnas.

**¿Cómo podemos leer un CSV en Python?** Con Pandas! [Aquí tienes la documentación](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/laliga.csv')
df.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

**Parámetros interesantes del `read_csv()`**
1. `sep`: el separador de los datos, por defecto es coma, pero podría ser otro como veremos en ejemplos posteriores.
2. `header`: dónde se encuentran los nombre de columnas. Por defecto es en la primera línea.

Probemos a leer el CSV desde otra ruta del ordenador

In [13]:
tu_ruta = 'data/laliga.csv'
df = pd.read_csv(tu_ruta)

df.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

Una de las columnas, la podremos usar como index

In [14]:
df = pd.read_csv('data/laliga.csv', index_col = "Unnamed: 0")
df.head()

,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

In [15]:
df.index

Index([26201, 26202, 26203, 26204, 26205, 26206, 26207, 26208, 26209, 26210,
       ...
       36675, 36676, 36677, 36678, 36679, 36680, 36681, 36682, 36683, 36684],
      dtype='int64', length=4940)

Si queremos pasar el índice a una nueva columna, simplemente creamos una columna nueva

In [16]:
df['nueva columna'] = df.index
df.reset_index(inplace=True, drop=True)

In [17]:
df.head()

,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp,nueva columna
0,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600,26201
1,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600,26202
2,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600,26203
3,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000,26204
4,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000,26205

Podemos resetear también el índice, y poner ahi un numérico que vaya desde el 0 al número de filas.

In [18]:
# Resetear el index. Drop= True para que no lo conserve
df.reset_index(drop=True)

,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp,nueva columna
0,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600,26201
1,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600,26202
2,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600,26203
3,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000,26204
4,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000,26205
...,...,...,...,...,...,...,...,...,...,...
4935,2017-18,1,38,Villarreal,Real Madrid,2,2,19/05/2018,1526680800,36680
4936,2017-18,1,38,Atletico de Bilbao,Espanol,0,1,20/05/2018,1526767200,36681
4937,2017-18,1,38,Barcelona,Real Sociedad,1,0,20/05/2018,1526767200,36682
4938,2017-18,1,38,Valencia,Deportivo,2,1,20/05/2018,1526767200,36683
4939,2017-18,1,38,Atletico de Madrid,Eibar,2,2,20/05/2018,1526767200,36684

In [19]:
# Para cambiar el indice
df.index = range(1, df.shape[0] + 1)
df.head()

,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp,nueva columna
1,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600,26201
2,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600,26202
3,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600,26203
4,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000,26204
5,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000,26205

In [20]:
# Dimensiones
print(df.shape) # Ambas
print(df.shape[0]) # Filas
print(df.shape[1]) # columnas
print(len(df)) # Filas tambien

(4940, 10)
4940
10
4940

In [21]:
df.head(2)

,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp,nueva columna
1,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600,26201
2,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600,26202

También es posible aplicarle nombres de columnas en la lectura de los datos

In [22]:
df.columns

Index(['season', 'division', 'round', 'localTeam', 'visitorTeam', 'localGoals',
       'visitorGoals', 'date', 'timestamp', 'nueva columna'],
      dtype='str')

In [23]:
df = pd.read_csv('data/laliga.csv',
                 names = ['Indice', 'Temporada', 'Division', 'Jornada',
                          'Equipo local', 'Equipo visitante', 'Goles local',
                          'Goles visitante', 'fecha', 'timestamp'],
                header = 0)
df.head()

,Indice,Temporada,Division,Jornada,Equipo local,Equipo visitante,Goles local,Goles visitante,fecha,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

In [24]:
df.dtypes

Indice              int64
Temporada             str
Division            int64
Jornada             int64
Equipo local          str
Equipo visitante      str
Goles local         int64
Goles visitante     int64
fecha                 str
timestamp           int64
dtype: object

Si queremos cambiar los tipos de los datos, en la propia lectura

In [25]:
df = pd.read_csv("data/laliga.csv",
                usecols = ['Unnamed: 0', 'division', 'localTeam'],
                dtype = {'Unnamed: 0': str,
                         'division': np.int16, # np.int64
                         'localTeam': str})

df.head()

  Unnamed: 0  division           localTeam
0      26201         1  Atletico de Bilbao
1      26202         1              Alaves
2      26203         1            Valencia
3      26204         1  Atletico de Madrid
4      26205         1               Cadiz

In [26]:
df.dtypes

Unnamed: 0      str
division      int16
localTeam       str
dtype: object

**¿Cómo leer un archivo CSV que no esté separado por comas?**
Probemos a leer un archivo CSV, que no tiene comas como delimitador

In [27]:
df = pd.read_csv("data/laligaPC.csv")
df.head()

  Unnamed: 0;season;division;round;localTeam;visitorTeam;localGoals;visitorGoals;date;timestamp
0  26201;2005-06;1;1;Atletico de Bilbao;Real Soci...
1  26202;2005-06;1;1;Alaves;Barcelona;0;0;27/08/2...
2  26203;2005-06;1;1;Valencia;Betis;1;0;27/08/200...
3  26204;2005-06;1;1;Atletico de Madrid;Zaragoza;...
4  26205;2005-06;1;1;Cadiz;Real Madrid;1;2;28/08/...

Lo lee todo como una única línea ya que no encuentra comas. **Se recomienda trabajar con CSVs cuyo separador sea el ; así evitamos problemas por los decimales**.

In [28]:
df = pd.read_csv("data/laligaPC.csv", sep=';')
df.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

¿Podemos tener otros caracteres que separen los datos?

In [29]:
df = pd.read_csv("data/laliga4.csv")
df.head()

  Unnamed: 0~season~division~round~localTeam~visitorTeam~localGoals~visitorGoals~date~timestamp
0  26201~2005-06~1~1~Atletico de Bilbao~Real Soci...
1  26202~2005-06~1~1~Alaves~Barcelona~0~0~27/08/2...
2  26203~2005-06~1~1~Valencia~Betis~1~0~27/08/200...
3  26204~2005-06~1~1~Atletico de Madrid~Zaragoza~...
4  26205~2005-06~1~1~Cadiz~Real Madrid~1~2~28/08/...

In [30]:
df = pd.read_csv("data/laliga4.csv", sep='~')
df.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

In [31]:
df = pd.read_csv("data/laligaPC.csv", sep=";")
df

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000
...,...,...,...,...,...,...,...,...,...,...
4935,36680,2017-18,1,38,Villarreal,Real Madrid,2,2,19/05/2018,1526680800
4936,36681,2017-18,1,38,Atletico de Bilbao,Espanol,0,1,20/05/2018,1526767200
4937,36682,2017-18,1,38,Barcelona,Real Sociedad,1,0,20/05/2018,1526767200
4938,36683,2017-18,1,38,Valencia,Deportivo,2,1,20/05/2018,1526767200
4939,36684,2017-18,1,38,Atletico de Madrid,Eibar,2,2,20/05/2018,1526767200

**Escritura de CSV**

Para escribir un CSV usamos el método `to_csv()`. Tienes [el enlace a la documentación para ver más detalle](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html).

In [32]:
df.to_csv("data/laligaWrite.csv", sep = ';', index = False)

In [33]:
df.to_csv("data/laligaWrite.csv", sep = ';')

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio CSV</h3>

Crea un fichero de CSV llamado ejercicio_clase.csv en la carpeta de data a partir de estas Series con separador de ; y leelo a continuación.
         
 </td></tr>
</table>

In [34]:
dummy = {"colA": range(5),"colB":range(6,11),"colC":range(20,25)}
df_dummy = pd.DataFrame(dummy)
df_dummy

   colA  colB  colC
0     0     6    20
1     1     7    21
2     2     8    22
3     3     9    23
4     4    10    24

In [35]:
df_dummy.to_csv("data/ejercicio_clase.csv", sep = ';', index=False)

In [36]:
df_dummy_read = pd.read_csv("data/ejercicio_clase.csv", sep=";")
df_dummy_read

   colA  colB  colC
0     0     6    20
1     1     7    21
2     2     8    22
3     3     9    23
4     4    10    24

## 4. Excel
¿Qué empresa no trabaja con Excel? **Nos vamos a encontrar los formatos de datos de Excel en cualquier sitio**. Las extensiones de archivo más habituales son `.xlsx` y `.xls`. Por suerte, **`pandas` tiene métodos para leer los formatos de archivo de Excel**.

El problema que presenta este tipo de lectura de datos es que **no es un formato tan cerrado como el CSV**. En el CSV tenemos una estructura compacta, con todos los datos separados por comas y con una línea de cabecera en la primera fila. El Excel permite tener datos en un formato mucho más flexible, con tablas en cualquier sitio de las hojas, información en varias hojas y demás.

Teniendo esto en cuenta, y sabiendo bien el formato del Excel en cuestión, podremos leerlo sin problemas con `pandas`, debido a la cantidad de argumentos que tiene la función `read_excel`. [En la documentación tienes todo el detalle](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html).

Leemos nuestro archivo de laliga, pero en este caso en Excel

In [37]:
# %pip install openpyxl

In [38]:
with open('data/laliga.xlsx', 'r', encoding= 'ISO-8859-1') as open_file:
    all_text = open_file.read()
    print(type(all_text))
    print(all_text)

<class 'str'>
PK
     odX               _rels/PK
   odXj¿¼Ææ   J     _rels/.rels­ÁJÄ0_%Ì};ÝDd³{ao"õÆdÚ-m3!µûöFba<d¾ÿûÃl÷ó4WN¹`a]Õ`88ñ}è,<5÷«0Y)x%°gØï¶<|ìc6²£j¼EÌîÈåJ"rÓJHË1uÉ
Ô1nêúÓw,¦¡Ô±ZðâÄcUh`SäßdIÛöïÄ½LôL$ò¬<ûU,	´/ÝÌÁ[HøÄSº\'Vò¤ôI='´¹(4ø&ixþû/¾\Ö.¸ØÝ;PK
     odX            	   docProps/PK
     odX               xl/PK
     odX            	   xl/theme/PK
   odX¹B$¬  u     xl/theme/theme1.xmlíY[oÛ6þ+Þ[ù&Ç
ê/Í¦
·CiXS¢@ÒIýV´ë½ØÛmZ`/Ý¯ÉÖaëþ]lQ6%í2thmÀ¿sç9"å«×!)ºVýrÍB$r¹G#¿kÝ
/u,$<ÌxDºÖHëúµ«xS$$(Â!oO&Ô%h,#¹»V T¼iÛÒ:yL"pbCáÛÀÇ )dv£VkÛ!¦µ>`ð)\&Ý5)ÖÖËa©àÚµjéÇBGu-Pâñãy ,ûÚU{ÉÄw~J¼9_ÎàM)ðÇ	ckµV{k)¿É_Ç
6íA{)/`×Oë^+Çj ìÖ »¿ÑoÖKxM~s
¿å$ß¾Yà[køá°UÇ·
¼³w¶¯l÷Ëòß^ÃoÔ¶ú­>FÓ5t`HS^B&íáwÆ([[]¤ªÖZïs1@\¬hÔ<&ì®Ã± 8Q7	Öf2+×H.øúÅ¯_<C¯_<=yôüäÑÏ'<ú
Ð4V]ëãGFÆWß}þ×7ÑÏ¾}õäË¿#ßÿíÇOýåP/¿zúûó§/¿þìïàÑHt£­K-ÇçãØ!caæÀ à(À¼5ÇLÃ
T`ÆÝPápTDí03EàÙ}³{³m.twv°ÂYäkÊwSL¸JºÅÌÌbX»TÙ«Jî><bDD¡^@¢±Åìu|¢Ð=¶1ÕCrRs¦B^æzéØ¼öî¢mÎh)×æèìÁJÇ¬ öÉxÏuy«@7Ìp© Ó>a
<"¥Æs8®gCïÑÓ~[ÌÍöîb¡èTCî±yhDöù´à0Ö°71çFìGr
K£}®tsiT¬çÈ<àh5ÝÉÄùÊú.%¹^.;Ôf¢`IÆæz³	&ð¼¿:uH£ÓÚ6£Ð·ßç¶½-vf½û?·è>EûÖûý¡C¿z¥ÿ³¾\´b[ßk§bÂÊ÷2v¨æÜià¬7b:Hûü8Û\]	çÞ#ÁÕ'TAM=ÕàË\´/QÌ%.¬JÙéÏÙ!§ Õ÷2r³V+ÎJK1éÈº¢f"à¬Êo§¬OÕVì*ØÖÇxILNÞ ÔÛ
Ý²E.2ucêÍ3¨óÏñ)Õ·SvlÚ®´*´9"{½ìXT!Ìü¨k¹
ÚÆ UB»A.»Ö6Z:³c­hÓ {$wØ1ú[«ô·¤!Rõ±2®tjñÖ%:ù
§µHÑ4Éf§~qVØ«%	qU¥æs|¦8¼cäQØÊ_½ð4h4ÓÙ1Þ¶X}»Ó1÷£ûÞ/mHGyvíï+ÎûëJ²raWÛôÒ<íFÉíZ\¨CêìR]`4ä(µ%oª+VÉ5ÓÉÈz¨êgnC
]Nýaõ¼óE.å}fi®³ë6J³øo¡`Ñ,ò@¤¸Õ¤Ù¦êûÃwxÓªØà¾5(iKéÊ´Gªö$¸òv&ïAÛ0;ÜpÎü áhèëT¸¬ØÅø$-÷VÜ¥N^KâLîh¾%¢.vua»É"¬°®íÍÃê¢êT{½mí`Öþâãû »§S2{ô ½Åß
 Ç.X¯ý
PK
   odX*}n  8     docProps/core.xml¥]OÂ0ÿÊÒûítl¶¨áJ1ïö ëGÚêàß;£ÜyÙ¼Osú¶ït|¡Êä%	a¥2¼¬é$!r#yk
ÖdÌJ8&¬Ç'oú¨0$½Ç&\M¶1:Ä5YO>\[¯yì~¾A((ÆÈ%ÂÔFrRJ1*Ý§o-j41@åpa#z®^¤Vqïð*zGzv]uåöûçð¶||*shJ i*)ðÈ£õ0Õò}«kòn`ØçH¡Lú	ì¸Ï9y-ïVÒ´¤´LédìfÊJÑÛÙ{¿©>Múõ,i*øóÛÍ7PK
     odX               xl/worksheets/PK
   odXÕ°K=- ýí    xl/worksheets/sheet5.xml¬½Ý²ìÆq­û*Þo±*ÔBÒ­Ùè«'ÎÏ5MQÃ"© )Ë~ûÓk°W
Â¶äÌÙUÙßB_eøÝÿüoÿúÙ¿ýÃß|ÿÝï?~sûü³¯¿ûêû?}óÝ¿þþóÿçÿ¾ÿöùg?þôåwúò¯ß÷õï?ÿÏ¯üüþáwÿøþûñ/_ýÓgÏ¿ÿîÇßþ~úÛo¿øâÇ¯þòõ·_þøïÿöõwÏÈ¿ÿáÛ/zþ×þõÿöÃ×_þéý¾ýëóíV¾øöËo¾ûüðÛ"ñýÿüÍW_ÿñû¯þþí×ßýôÏùáë¿~ùÓsö?þå¿ýx|Ú·_E>îÛ/ø·¿ÿí|õý·{~Ä¿|ó×o~úÏ÷ýü³o¿úíþ¯ß}ÿÃÿò×gÕÿ1å/¿:>ûý¿ÐÇûÍW?|ÿã÷þé7Ïûy¢\sÿ¢ñü¤?üîýÿ÷~øÃï¾ÿûOýæ»¯ÿÏýø÷oúÏõë¿~ÿß~ûü?üîÿJûÓ7Ï?Búì¯ÿüûÏÿ×ôÛGîuùôóÿ~óõ?~üä?öÐ¿|ÿý¿}ü/ûÌç}{ÿ:£ÿéë?ù÷¿þô}ÿíëoþõ/?=ÿ1,Ï?ÖúÛ?ýç¿þñ«ç7þüßÌï~õý_|ÿß}ûÍÇ8ÏoìËÿxÿ¿?þô¿²éù%þã?ýôç¼ýf©%Ïm©Óûÿ?ÿì«¿ÿøÓ÷ßþ?'|þÙ¿|ýãO÷o>úó§ÿósç?wþïÏ­~nNéøÐ)§ðÇ¦?6yÓíg?5ÿü©ÙûÔö)×öß;?vùùcÿþØö_;ÿnËÏ[.þÜúóçV÷ßÂtúsÛÏÛÜÏÓÊ<ý÷·ðçö?·_ûolºÇÄí&üâ?/þyÌ½¶üò§/ÿð»¾ÿÇ/¡ýðþÿüÀÿ: ?ÿìýÿ´ß<83ýô¿>±ï¡gäÇçÿ÷ßÿpûÝÿþq´3ÖfÌdL6ãógÌ6ãlÆÛ?3Ò'ÙfÜ9c±xb36Î¨6cçjÍxðgôÿÊøâdÄeqßGÉÿü6Ë|ï|ýg|ùçwÙ|[ÿûÓ¿¿ý£½Íô-Oðâî¤À§|øt ½}Þ¡ªû03æåÖS¹Ý^úúSèëOðõÃ?è5
¾þ$¾~{KüÝÂÐw'¾âé¿âMÄö4øúÓ¯ÿúsèëÏðõCk|ýY|ý"öù»Å!'[_|ýù×ýKèë_àëï`]_ÿ"¾~{[ø»_ð»?áñ¯_Äv¨ªÃ÷XàëÚíöâ×_B_¯þ}­eðõñõØ[áïN~w'¥Ã×/FØLeðõÁ×_~ý×_C_¯þ	®uðõWñõØ[¥ïvÆS¯§ÞúË_ñVÅ¿þ:øúë¯ÿú[èëoðõÃá½¶Á×ßÄ×/bo¿[<õ:)xêmâÇ§ýmðõ·_ÿõ÷Ð×ßáë_µ¾þ.¾~{ëüÝâ©×IÁSo_¿}ï¯¿ÿú¯ÿ£Fì à÷uý9á	O@*øösÐ|Ãxörðlk@3Ø±8aÿú$ OÐús 1)"ø6±íÎx.örðd¬ÙLÏX. á	l}sF:<)¶$Ý]çàqóAÍ`Cq¯hqI·4¿J"æÅ1Úé:ÌxRjl?I°ùâïÿÝÉAø f°MÊ¡8DºDL'pd\X§$OÊíÇ#	G;à¼ý ÙL0!<"/ ³å	tÖiäËfûñHÂñá$8/­>¨A¶IY3WPÓ$ZuÙbóæ?Ôë4RçI¹ó$ôõmb5F9¸;9xQñAÍ`SÁsHHÄzÆáuYô¤4zû6-ùîåÌHBÌ`S3Ø¡8D½DL§'ði\.[§POÊ¨'!µo#Ìtà\uú0)«VÓÛ¡8D»DÌ¬'Pk,sFn=)¹¶$Øñ"úîåÐ1!ÙÔôv(Î!Ñ=9æØ386^¼¬óÈ±gåØ³Ðß·yìÏw/	5Mw(IÌ·HÄ{ÇÆKÄu9ö¬Û~<`ÆÇ»×NjMw(Î!1]@"ØpÇÆSæ:[Î²ç,ZÂo³ãÏ¸øçäpÛùÓA$!,â
þð=ftì~k¯®vÌ1ÇÁ±ñÂdG=+Ç6A"áø3{ø[ÁsH c!sì/è×yäØ³rìYîÛì86íÄp	ÕïP\A±|ÌèØ½çü*cÏàØøó°Î#Çc ´¥½l
ÍÊ±Õôv(Î!}DÌ±gpl<ô×yäØ³rl$?ã
 ý	ú
îPCûcÏàØ¸ä¼Î#Çc `¦½NuÔ6Ü¡8:ö1ÇÁ±±Ìu9ö¬ÛãØt{øY9¶ÞÅ9$Ð±Ï9öÚ´Î#Çc ûóÝÉ¡-jÍ3è#èØ'H¤c'plü·¦c'åØ&$ãÏ´sh+Áf´ò6 Ð±Ï9vÇNèØiäØI9¶		§G×N^®v¨l&H$¦	tì3$bÀ±:v9vRmI8þý	/W;ÐèM÷«	»ÎËëÛ»û»Á±mðîð[¼"èc;9´ÍXÍ`SÁ=¡ctc'pìFc pü	'	åØ*¸'tl"/ sìÐ±ÓÈ±rl$NûNõ'Ì tëêc'tl"±\@"æØ	;¡c§c'åØ&H$>6öì¼"¡úØI9vBÇ&å1ÇNàØ	;;)Ç6A"á86NîwJBä·¤úØ	HÔHÄ;c'tì4rì¤ÛãÏ¸ÚáäP;)ÇVÁ=¡cvc'pìFc'a¸oÉñgìÙy9¸ËFÍ`K¢É½'tl"Ñ=sìÐ±óÈ±³rlDÙñg$áäÐ¾Ø,D~SÓÛ3:6È·HÄ;cgtì<rì¬ÛÓ£Æ3¶ÇD"¿©éí»"	pìòË{ÅsÌ±38vFÇÎ#ÇÎÊ±³h1¿eÇqµÃÉ¡À,¶ojz{FÇîH{æö*cgpìGc ûóÝË!Ê±M×b3:6@Ç>C"x;58v¦û©7TË;ª³"áø3®Åz9Ø)R3Ø²êcgtl"}DÌ±38vFÇÎ#ÇÎÊ±MH8þLw·;9¸£ÀÖ$T;£c	tì3$bÁ±3:v9vVmDbÜ£¾;9´ËFÍ`SÁ=£c	tì3$bÁ±3:v9vVmDÂñgì:9Ô=5Ð[Ýw
ÅTGFÇ^zõNsìÑ±óÈ±³rl$>¶mk@ª
Å9$Ð±Ï9vÇÎèØyäØY9¶	@ÛË¡cBÝE{âèØ'H,1Ç^À±3:ö2rìE9¶	"Åñg<c{9xÆV3Øaù;Ç$tì3$b½c/èØËÈ±åØ&H$}l'V m
HBõ±¡8:ö1Ç^À±tìeäØrl,H"ÐÇörè)Aª­;WðÂcÇnÓT_~PSÌ±pì{9ö¢ÛÓÇ&ãýäl
HBõ±¡8DºDÌ±pì{9ö¢Û³WûN­«l*¸Cqõý±c·ù_]\O/Ç^èñeÃçÉ-ÓÇÆu'/WÅÍ ô3åØPCb¹DÌ±pì{9ö¢ÛãÏØ=ur¨{ºVõfDeD¢\@"æØ8ö½{QmDbìÏw'öv¨lêc/èØD¢^@"æØ8ö½{QmDÂéQÓ1áäàºÁ¦ûM$Ú$b½c/èØËÈ±åØ&H$Æþ|wrhçÙ"åÛ"|_Ð±Dÿõ$JÌ±8ö]F]c (ã{­ï^þ:©l*¸tl$Qn9vÇ.èØeäØE9¶		Ç±qUÜÉ¡>¶ûØjz{AÇ&Ó$b]À±:v9vQmIúØ^=
Võ±MW ¡¸û)»§¹¾ºÚQb]À±:v9vQmDÂñg\ur¨{ªf°©àÅ9$Ò$b]À±:v9vQmDÂñg4;'vAè×I=ósHäHÄ»ctì2rì¢ÛÓ£ÆNC¢¢[Moâ
î1zpì§wàÃÂÁ±=-|ø¸pù¼ð¢HîÇvrh¿ÁVïPC¢\@"æØ» ccåØ&H$ÆÏ3»;9Ô(ª]cCqzcpì]F]c pzÔØ³órèÚIíWÁsH´HÄ»ctì2rì¢ÛãÏtØ+^Ävð­(Çâý×¨1Ç®àØ»»*Ç6A$Q½âxL89ünõ\q5½cõvcWpì]G]c <óÌË!¢U½©éíPCbºDÌ±+8vEÇ®#Ç®Ê±M°!@ÛÉ¡NQ½U!à{EÇÆÕÝ?>BùE1Ç®àØ»»*Ç6A"áø3® :9Ô°5 ¤H c	tì3$b]Á±+:v9vUmD"ÐÇörð­f° @ÇÆ·ÿÙÒí6µWQc]Á±+:v9vUmDÂñgtl/	1­
ß+:6X. sì
]Ñ±ëÈ±«rl$ç;9´ßÉÏÆ¬ª]Ñ±D¹DðÝ\àØ^Î5|;|=WU$Ïwr¨{j!ò]èØD¢^@"æØ»¢c×cWåØ&H$ÏwrhoGU­¦·Wtl"Ñ. sì
]Ñ±ëÈ±«rl$ç;9t'KU]cWtl"Ñ=sì]Ñ±ÛÈ±rlDmü<³»;
Ô¶&|oèØHÂ~ôI1ÇnàØ
»»)Ç6A"èc{9DBõ±ð½¡cé1ÇnàØ
»»)Ç6Á$o³vrhPÍ`SÁ+¸õaÿúIbIåÕûìZÌ±8vCÇn#ÇnÊ±MHîÇörpU¼	ÞðsH¤HÄ»c7tì6rì¦ÛãÏ¸*îäÐ5Mw(®à®àGCÇþø|¾WIÄ»c7tì6rì¦ÛÄøáw/×bÍ èM96ç@Ç>C"æØ
»¡c·c7åØ&H$¦wÿßý¡Võ¦;ç@Ç>C"æØ
»¡c·c7åØ&H$Ç¦óC¯aV{Årl(Î!}DðUØàØÞ=|¶|vS$}l/	µW\w(Î!}DÌ±8vCÇn#ÇnÊ±MHúØ^®Å6åØM96ç@Ç>A¢Ç»c7tì>rì®ÛDô±ÚÛ¡f°©àÅ1}DÌ±;8vGÇî#ÇîÊ±MHúØNí(P3ØTpâèØgHÄ»cwtì>rì®ÛoÂh¼xrr¨i§¦°©àÕÜ*ÿè ÙÓQÄ$»dãkÓ×>ì®$Û	cÐ¸ëäÐ5­+Ëêé1Ëî`Ù-»,»+Ë¶AB1Vè»CË±j
[W­l¨ÎA/@ÓìÝQ³ûH³»Òl$Cã®'ÖcÕ6[!¢ ÏÆ;H<{Óôê§óìÝÑ³ûÈ³»òl$N3dÚjÓE¿zSóÛ¡:E¹ EL´;vGÑî#ÑîJ´mP-úîäÐý,j
	âý,P¢^"fÚL»£i÷iweÚ6H(¦Ó¶MT5Mw¨ÎAÑ.@SíªÝQµûHµ»Rm$GcÕÉ¡=j

îP¢ÿzÓ-&ÛïyÚöñË4ìg "#,ÛÚnö+ä46ÅK),¡À§¥ï÷¼O¨¤÷¡¨(÷(SqÔ/©¼$ÚcÂ%sÝ±HÊt¿ç*háG¢¢<¢Q	l)÷hUJ!*jW9Yðáp,#ÝæúòS¹¦[ÌÇßóò#CQQJQ¦h}{IÔqRÊ§Q¼ÖÂ"=*Øÿ>E%¦æïy
ºù¡¨(;(S	ÜÎí%Ñ;nÓÜ±H
öÂOQYú{¡~d(*JÔ!ÊTÆ~wp1QNc³QþÃ¶8SÁ¾ø)*1aÏ3TÐØEE9;DcíØòh×ÄÇÚEzT°G~JÌÝßó÷#CQQúQ¦2~õ×ÝMÂ­©¨n9Yð¤,ãùS_^~fÎtiü{¡d(*Êä!ÊTmçØ
ñ¨[+§±ÉèEzT°w~JÌèßóTú#CQQRQ¦Ø¦î%Ñ¾;+ªEzT°~ÊtûéTÈí§¡ÛOÒím¨LvºD{Lì@d¶P¤2aK¨LØS?E%èö¸=D×#CQno£L%ÐZ÷hÆ&£;éQÁþú)*A·Àíñk[EEº½ÎDeüÚ°»D+.°÷MFw,²à(cJsZò«»¨¤n_Ûzd(*Òím©·¬ßÝ$:¯t{(Ò£® tû	Ü]EEº½2ÇíiuÒI¢U|9ÍFùXÉC*ù
*A·ÀíñL»t{e*¶óyÅéÕÓ:Ø$ì}Ñô¨,WP	ºýnÿ×#CQno£Le¬íw7|eûÛ7(¨ÛãmÝ(ãI%çéÕÍ*Ótû	Ü½z=2éö6ÊTÆÚ~wpÏ©IîX¤G¥^A%èö¸=þ0¬G¢"ÝÞFJàe^w½l)DEº=éQiWP	ºýnÿN×#CQno£Le¼õýî&ñ±¢6ÈÛ(WúJ¿ÊtûÜ¯J×#CP¥ÛÛ(QÇs»{ItwV\Ô$w,Ò¡2ß® tûÜ=Ö#CQno£Le¬íw7®Í@t^1Qò(Ò£2]A%èö3¸=þ;]EEº½&¢âh;­9IÜ_¥Û«IîXdÁÛÃð÷O*}é/÷Wæ ÛÏàöø¾t{e*¶3§oÏTdß~æ¿ctûSTn?ÛãÔzd(*Òím©n_÷¸¿¢¦±ÉèE¼ÿ?¥tËååÕÉ9èö3¸=þz¬G¢"ÝÞFJàVv/×Í@øB9Éô¨,WP	ºýn'ÑõÈPT¤ÛÛ(S	<ÝM¢þÆ&£;éQ)WP	ºýnäë¡¨H··Q¦¸ÅÝM¢u°Yº½-¨Ô!z ÛÏàöXìzd(*Òím©8nÏ¿`ãúì@ì+Âüw,Ò£Ò® tûÜWÑ×#CQno£L%pë»Ä«³ìÛÏÂüw,Ò£Ò/ nÀíñ$ºJno£D%µýî&ÑÙ>Îü&£;éPI·+¨Ý>Û'rû4tû$ÝÞFJ¤oï$ñn$ÝÞJT¦!é
*A·OàöÜ>
Ý>I··ÑLT shÍXMcÑ,øÐüýÊRò«O|þU
¸}"·OC·OÒím©µýî%q8I·WÜ±HJºJÐí¸}"·OC·OÒím©·Ûß½$Þ¥§¦±Ù(­¸$t{¦nJÐí¸}"·OC·OÒím©nwÈWÔ46(¨ÛãÃfðéO*e¹½Ü·OA·OàöÜ>
Ý>I··Q¦xdÄ]¯$ûö&J+ùP¤GÝþ Û'pûDnn¤ÛÛ(S	¼ÍKâ¾½Æf£L¥© Û¢tûnÈíÓÐít{e*ûëÝ$¾{òt{(Ò£nJÐí¸}"·OC·OÒím©nµ÷¸Cdß^Ew,Ò£nJº}·OäöyèöYº½xºDWÆf :¯déöP¤C%£Û¢tûnoÞ]EEº½2À#å½$Þg¥ÛgéöP¤GÝþ Ûgp{|Üzd(*Òímt!*¶ÓyÅIâ|5ÍFélE|Ð>ý©/Sé/ï¦ÈA·ÏàöÜ>Ý>K··Q¦éÛ{IÔ·WÓØdtÇ"=*é
*A·ÏàöÜ>Ý>K··Q¦éÛ{I´¯¦±ÉèE|ÌÓþþIe^wSä ÛgpûLnn¥ÛÛ(Sôí$^3ÎÂÞ79Éô¨,WP	º}·ÏäöyèöYº½2HßÞIâ=.Yº½îX¤G¥\A%èöÜ>Ûç¡Ûgéö6ÊT"}{'wS¨il6ÊTÐíJ½JÐí3¸=¾¹t=2éö6ÊT"}{/zjJTÐíJ»JÐí3¸=¾ÿi=2éö6ÊT·ç+cÇíØu¿A¡DÝ©ô¨,A·_Àí3¹ý2tûEº½ÅÑvºóhuRMc³Qú[ÐíÊr»JÐípûÜ~ºý"ÝÞFJ¤oï$ñ>c5ÍF
º=S® tûÜö³t{-D%Ò·÷hÌBTäýöPdÅÇ¤= 'Z_
ÂtûÜÊ°t{e*¶Óê¤Dë`jÒéQA·?E%èö¸ýBn¿Ý~no£LÅiÉó±2~àÞ;íM©ä!tûSTn¿Ûãû×#CQno£LÅq{êEzI|¶÷Û«IîXdÅ"ð÷O*­Ü^ÞM±Ý~·Ç·¶¬G¢"ÝÞFÊXÛï^ï¦°¥y¿=éQA·?E%èö¸ýBn¿Ý~no£LÅq{Z3vxÞ"vÝo2ºctûSTn¿Û/äöËÐíéö6ÊT¯yw¨C¬¦±ÉèEzTÐíOQ	ºýn¿Û/C·_¤ÛÛ(SkûÝKâÝjîX¤GÝþtûn¿Û¡Ûéö6JTJ¤oï$ñn
3Ý)Qdßt¨tûSTn_Àí¹}º}no£L%Ò·÷ÈWl)DE>Kô¨ Û¢tûn/¦ZEEº½V¢yN¾Ä+.Eº}n_Ðí©C\Àí[zù
S	º}·Ç)¬G¢"ÝÞFÊx»ýÝM¢®Wö¾Ù(SA·§u°n¿LÓë÷Û ÛpûBn_n_¤ÛÛ(S<'ßKb*²oo%*èöL%_A%èöÜ¾Û¡Ûéö6ÊT<ÿEúöjò±nÏT+¨Ý¾Ûrû2tû"ÝÞFãöÔõòÈíìÛ«èEzTÊTn_Àí¹}º}no£LÅÑv¦éÛéöEöíº=S©WP	º}·/äöeèöEº½2ç1ydN÷íÕ46(¨ Û3v ÛpûBn_n_¤ÛÛ(SqÜÖÁ$îøL>K¯ Û3~tû
n_ÈíëÐí«t{%*uüz»»D¾R¥ÛWéöÝ¨ÔÛTn_Áí+¹}º}no£LÅÑvÚMá$ñqn¯&¹c_­ñ¿Ro¯ßo_n_Áí+¹}º}no£¨DúöN÷"Õ46(¨Ûãïã>}z^¬¶öòK
º}·¯äöuèöUº½2ç~{êz9IÜ·WÓØ P¢TÒTn_Áí+¹}º}no£L%²'ßK¢³}}{Ý±ÈGâÊxR)õõ'²× ÛWpûJn_n_¥ÛÛ(SÜoï$ñ±Æf£LeRY® tû
ní_EEº½2Àë½$î¯¨il6ÊTÊJ¹JÐí+¸=>Èw=2éö6ÊTmçóD+.UØû:¤R¯ tû
n_ÉíëÐí«t{e*¶E:I¼wRMcÑô¨´+¨Ý¾ÛWrû:tû*ÝÞFJäYz^­¸¨il2ºc~tûn_ÉíÛÐít{%*-Ò·÷è¼Ò¤Û«IîX¤C¥Ý® tûnßÈíÛÐít{e*¾½Ä÷¯è¼¢¢;éQ® tûnßÈíÛÐít{íDe¼Ýþî&ÑÆf£LÜ)øORúë}ûtûn_EEº½2ÈýöNïkÂÞ7e*iH%]A%èö
Ü¹t{e*¶SØK¢5ã&:óäEV|ÐãþþIe®¯¯· Û7pûFnßnß¤ÛÛ(Sq´ÁÆ÷?Øø¼"¥EzT+¨Ý¾Û7rû6tû&ÝÞFãö|¬ >Èil2ºcr Û7pûFnßnß¤ÛÛ(SqöäSßÞIâ¾}nß¤ÛCz Û7pûFnßnß¤ÛÛ(SìÉ÷hÅEMc³Q>Û·!v Û7pûFnßnß¤ÛÛ(S¼ßÞIâ]zMtæ79Éô¨ô¨ô Ûwp{|ïz*]º½>~þÝKâ]zf z+N}{(Ò¡ÒoWP	º}·ÇÈ­G¢"ÝÞFJä~{'÷¸hÅEMrÇ"=*ÓTnßÁí;¹}º}noG¸GÛùXqøXOËÛä$w,²âCQð÷O*µ·wSô ÛwpûNnßnß¥ÛÛãö|¬8Iäö]ØûÓ *èöLÝþ ÛwpûNnßnß¥ÛÛJÄí½$:Ûwéö]öí;º=='¿£Û·öúsò{Ðí;¸}'·ïC·ïÒíLÅÑvr{/Ï+Òí»tûnÏTÐíOQ	º}·ïäö}èö]º½©8ÚÎT"ÏÉ·y¿}G·g*èö§¨Ý¾ÛãÃI×#CQnoG`*Ûó/Øøaúì@Q{ò;º=SA·?E%èöÜÁ´t{;S<'ßK¢u°.ì}it{¦nJÐí;¸}'·ïC·ïÒíL%ò|/¯åsòM®ÓÑí
ºý	*ó-æöïy
ºýñËTìg ©a¹ââ&á±bB_Ñd*PäY*1·ÏûÊ§ãTFno?©LJ oï&¡¯À@DE¹=éQA·?E%æöïy
ºý¡¨(·&¢Øï%ÑV9ÍFñlEV|¬ó>}J-ßæWwSÌ·Û¿ç*èöG¢¢ÜF`*cm¿{It§ÁÛctÛ¿ç*èöG¢¢ÜF`*¶ã~0/véÉil2ºc|Û¿ç*èöG¢¢ÜF`*NßÁ·g*jO>L¨Ûã#Ððé©´ß)1ßbnÿg¨ Ûr{©Þç&áÞI;ÿ©¾=éQ)WP¹ý{¡nd(*Êía¦xÄTÄ[î69Éô¨Ô+¨ÄÜþ=ÏPA·?2åö0S	ìÉ÷è<;º½²¯´!vÛ¿ç*èöG¢¢ÜF`*=ù^Ý)ab*ê9ùX¤G¥_@e
ºýt*äöÓÐí'éöv¢2öä»I¸ÇB*&J¾E:T¦ÛTn?Û£Á­G¢"ÝÞÀT¾=ýyILEº½îX¤GeºJÐí'p{¼´YEEº½a&*ã[éï^u½ì@ô¦&¹cLÿ¿R¿Ýê«»)æ)èö¸=^®G¢"ÝÞÀTm§ÕI'W''aïäEzTÒTn?Ûã¥Ízd(*ÒíL%ð~{/º^v Üf£|^ÉC*ù
*A·Àíña=2éöv¦âh;ö"Ý$Z3VÓØl®¡È/qxÀ§¤Ò_~{Á<Ý~·ÇÎõÈPT¤ÛÛJ`O¾D{\` ¢¢úöX¤G¥\A%èö¸=þ\EEº½©8ÚÎ¿`NWÔ|9Éô¨Ô+¨Ý~·ÇÎõÈPT¤ÛÛ£í|¶/ |ºßô¨´+¨Ý~·ÇUôõÈPT¤ÛÛÊ¸%wø¼"Ý^MrÇ"=*ý*sÐígp{¼þYAenoG *óXÛï^í3ÓØdtÇ"*óí
*A·Áíñçz=2éöv¦Øï&Ñ:®M®Á HÊt ÛÏàöhpë¡¨H··#$¢éÛ{IÔõ¥ÛÛit{ÚM1£Ûi~y7ÅtûÜÿ1¯G¢"ÝÞÀTm§óDûÁì@L%ýò´ctûSTn?Ûã×¶t{;Sq´Vò$^TÓØdtÇ"=*èö§¨Ý~·ÇÎõÈPT¤ÛÛÊXÛïnõ"Õ46¥(²âkhðé©ôöòn9èö3¸=®×®G¢"ÝÞÀTï·÷xçÁdßô¨ Û¢tûÜ=Ö#CQnoG`*cm¿»Iü¦Þoo£|¬Ô!tûSTn?Ûc±ë¡¨H··#0Çíi7Ä»)fÑß`D¥
© Û¢tûÜ/mÖ#CQnoG`*ã[éïn_K·eßô¨ Û¡nÀí±ØõÈTt{;QIãW×ßÝ$Úã¢¦±ÉèE:Tºý)*A·OàöÜ>
Ý>I··#0HßÞKb*bÒyô¨ Û¢tûn+[EEº½!À;ðÜ$º3áxr;Yñå@øû)ßæ©¾¼"Ý>ÛãCÖ#CQnoG`*ÛSÅK¢®ÎöIÿEzTÒTnÀí¹}º}noG`*ÛÓD]/5ÍFJRÉWP	º}·OäöièöIº½©8{òiÍØKâcåÓhÍ8I·OèöLe¹JÐí¸}"·OC·OÒíLÅq{>V·§®Æf£´Ðíñ]EðéO*é^ÞãnÀí¹}º}noG`*¶ÓÄ«jîX¤G¥^A%èö	Ü>Û§¡Û'éöv¦âh;_9 |¬È=ùIÿEzTÚTnÀíña?ë¡¨H··#0GÛi7D»)tû$Ý>¡Û3~tûn·4¯G ¥ÛÛJv´®$ÞÑÅ®ûMNrÇ"*öïÏR	º}·ÏäöyèöYº½©8ÚNÇDÇÆÓ *èöLeºJÐí3¸}&·ÏC·ÏÒíQ?ÿî%ñqnEWÇ"+¾ÞìE>©´y~y7Eº}·ÏäöyèöYº½©8ÚN¾â%Ñ:Xö¾Á4JRA·?E%èöÜ>Ûç¡Ûgéöv¦2~þÝKâ®Æ&£;Yñ¥søû'~{ùÍsº}·ÏäöyèöYº½©¥ç&ñ/¸£~³Qþ[TÐíOQ	º}·Ç2¬G¢"ÝÞÀTïÀóxïd»î7e*eHÝþ Ûgp{¼!p=2éöv¦xÄ½H;QQÏÉÇ"=*èö§¨Ý>Ûgrû<tû,ÝÞÀT·g*N+Ä×`ê9ùX¤GÝþ ÛgpûLnn¥ÛÛÊXÛï^ïhÍÂÞ79Éô¨ Û¡²Ý~·ÏäöËÐíéöv¢²8nO¾â%Q/RMci (Ò¡² Û¢tûÜ~!·_n¿H··#0HßÞIâÝjîX¤GÝþ Û/àö¹ý2tûEº=@T"}{'É9VÔsòaDÜ_Ðø"§<å¹¼¼b	ºýn·4¯G¢"ÝF *=ùN÷"aïÒÙô¨¤+¨Ý~·ÇÛiÖ#CQn#Èýö^õWì@DEº=éQÉWP	ºýn¿Û/C·_¤ÛD%Ò·wxÁä³ô HÊr Û/àö¹ý2tûEº=@T"nï%ñ±"Ý~nEV|Åì|RY¦ßâ9/A·_Àírûeèöt{¨ï%ñ.=5ÍFJR©WP	ºýn¿Û/C·_¤ÛD%ð|/»^ìÛ«èEzTÚTn¿Û/äöËÐíéö0Q	<'ßMb*²o¯¢;éQéP)A·/àöxCàz*Eº=TJä9ù^õWÔ46¥=.P¤C¥Ü® tûnÑ×#CQn#GÛÉW$ÞMa"*Òí¡HÊt ÛpûBn_n_¤ÛÛ*Q<KÏIâ®WùMNrÇ"+¾böÿ¼.¾¥éåÝ%èöÜ¾Û¡Ûéöv¦2Öö»ÄÇtû"Ý¾ Û3t ÛpûBn_n_¤ÛÛ£í´:é%ÑJ~»î7Ý±HJ¾JÐí¸}!·/C·/ÒíLÅÑv²H/º^j2t{|_$|úÊ4½ü¾È¹Ý¾Ûrû2tû"ÝÞÀT<õW$îéöj;éQ)WP	º}·Ç7Ö#CQnoG`*cm¿{I¼KOMcÑô¨Ô+¨Ý¾ÛãVÎõÈPT¤ÛÛJä~{'ûöv ¢"¥WÐíJ»JÐí¸}!·/C·/ÒíL%Ò·÷Ø"Å46Ý±HJ¿J
º}·/äöuèöUº½¨ÔHßÞIâ­Utæ79Ét¨ÔÛTn_Áí+¹}º}noG`*gé9IÜ·WÓØ`DÝ©LWP	º}·¯äöuèöUº½¡ñëíîn­ä«il0
¢n/É~À§ìy¥òòntû
n_ÉíëÐí«t{;Sqúö´:é%ñ±"÷äWaþ;éQA·?E%èöÜoXEEº½©·Ûß½$îÛ«il2ºctûSTn_Áíq#Ôzd(*ÒíLe¬íw7úöUØû&£;Yñò(òI¥Î¯¿°Ý¾ÛWrû:tû*ÝÞÀT"}{'Wò«èÌor;éQA·?E%èöÜ¾Û×¡ÛWéöv¦yÄ¿`rO¾Ò3Z¡H
ºý)*A·¯àöÜ¾Ý¾J··#0HßÞIâ^d}{5Éô¨ Û¢tû
n_ÉíëÐí«t{;Sôí$ÞMa"*Òí¡H
ºý*-èö
Ü¾Û·¡Û7éöv¢Òm'*^ùÝ±HJC·?E%èö
Ü7
®G¢"ÝÞÀT"}{/5MFw,Ò£nJÐí¸=n#XEEº½¡È|'W\Ì@´£UMrÇ"k§^dC·o}y¹ÙnßÀí¹}º}noG`*¶Ó±Ä{òÕ46Ý±ÈÚi¬¡Û÷öúýö-èö
Ü¾Û·¡Û7éöv¦âh;u½$îEªil6Êçt{¦nJÐí¸}#·oC·oÒíLe¬íw/÷¸¨il6ÊTÐí
ºý)*A·oàöÜ¾
Ý¾I··#0ñ#ðïnuìÛ«IîX¤GÝþ Û7pûFnßnß¤ÛÛ£íÔtxÆf£|¬ Û3tûSTnßÀíq#Ôzd(*ÒíLÅq{êE:I¼w²É¾}æ¿ctûSTnßÀí±	·t{;SkûÝKâ¾½Æ&£;éQA·?C¥Ý¾Û7rû>tû.ÝÞ@Túx»ýÝM¢k05MFw,Ò¡ÒÑíOQ	º}·ïäö}èö]º½©8}{úsxçV\Ô$w,²vzT·O·òúýö=èöÜ¾Û÷¡Ûwéö&/Gx;ÂÚ"$^ÉWÓØlÎ+Pd»ÑÜ>ÍyzùNtûnßÉíûÐí»t{u¨8ÚN+ùN÷íÍ@|¬È=ùP¤G%]A%èöÜ¾Û÷¡Ûwéö&êPôí$^3VÓØ P¢TòTnßÁíqÁzd(*ÒíMÔ¡éÛ{Iü&Ý^Ew,²Ýf¢nÒ\_^ìA·ïàö¸½t{u¨Dúö^­äwéö]tõw,Ò£R® tûnßÉíûÐí»t{u¨DúöNïqéÂÞ7Ý±HJ½JÐí;¸=6Ö#CQno¢Èsò$vû.Ý^MrÇ"=*í
*A·ïàö¨Oë¡¨H·7QJ¤oï$ñn
3+ò~{(Ò£Ò=t¹ý{¡ndü2ûHÅFÊ}{/öÛð­86T°H¦E¥sû÷¼O¨,7tû#CQQno£@ßÞK¢=.r2iHÝþÛ¿ç*èöG¢¢ÜÞFñ{oGXöíÝ$\ÓØdtÇ"Û
×ÁàïTZ~ùÝésû÷<CÝþÈPTÛÛ¨C%°'ßK¢®DTÛctûSTbnÿg¨ Ûr{u¨_]÷h%ßg{9Éô¨ Û¢sû÷<CÝþÈPTÛÛ¨Ce¬íw/úöv ¦"´·cíkÆPäJ_~·jºÅÜþ=ÏPA·?2åö6êP	¼ßÞK¢|(¨¨¾=éQA·?E%æöïy
ºý¡¨(··QJà9ùn+ÊíetÇ"=*èö§¨ÄÜþ=ÏPA·?2åö6êPqÜ'¯ÁÛÛ(SA·g*èö§¨ÄÜþ=ÏPA·?2åö6êP	Üoï&á:åöX¤GÝþ)èöÓ
¨ÛOC·¤Û(S÷Û»IØõ²IÿE:T&tûSTn?ÛãÏõzd(*ÒíMÔ¡xN¾Dg{3¾é¦ATÐí
ºý)*A·ÀíÑàÖ#CQno¢ø¢ö·#,»^n­©il2ºc
?ý?åçÿ¼üvè4Ý~·ÇëõÈPT¤Û¨CÅÑvìzyI¼6	{ßä$w,Ò£® tû	Ü× Ö#CQno¢GÛiÅÅKâóêÛC¡D%©ä+¨Ý~·Çë¡¨H·7Qãö´ï%Ñ:Æ&£;éQY® tû	Ü§³t{u¨o¥¿{IÔ·ÓØdtÇ".ú<àïTôòoÓtû	Ü§³t{u¨DÜÞI¢]zrJTêJ½JÐí'p{\¯]EEº½:TïÀóhçÆ&£;éQiWP	ºýnW¥ë¡¨H·7QJ oï%ÑÞI(¨¨÷Ûc~9èö3¸=i×#CP¥Û(Sm'_qh7Æ&£;éPoWP	ºýn®°t{u¨8}{êzyIdjîX¤GeºJÐígp{tõÈPT¤ÛhJD%Ò·w¸©¦±Ù(­NB
¿|úJ//ßoæ ÛÏàöx¦]EEº½:T·§|/ÖÁféö*ºc
¿9åå¶¼|WQn?Û£2¯G¢"ÝÞD*¶Óê¤D;Zí@LEÝoEzTòTn?Ûã7²t{u¨µýî%q×KMc³Q¦²©,WP	ºýn¿ë¡¨H·7QJà9ùnuÕ46e*àöøñORÒËwà¥9èö3¸=*ózd(*ÒíMÔ¡xN¾Ä{\fÙ·¥ÛCz ÛÏàöxi³t{u¨öä{I¼wRMcÑô¨´+¨Ý~·ÇKõÈPT¤Û¨CÅq{þshÍXMcÑô¨ô¨¤ Û'p{<®G ¤Û(SI¶Ó5Ä»)èÌo6Jç(Ò¡nWP	º}·ÇMóë¡¨H·7QJà9ùnùÆiHeºJÐí¸=nwXEEº½¦LTm§þÄë`f >V¤Û't{ÚMÀí§Ú¿¼"Ý>ÛãBÕzd(*ÒíMÔ¡â´äi%ßK¢ü$Ý^MrÇ"=*èö§¨Ý>ÛãOÌzd(*ÒíMÔ¡¸ßÞKâqndß>¡Û3tûSTnÀíñk[EEº½:T·ç_0':ÄIØûÓ *àöxz}@O*5¿ünÕnÀí¹}º}no¢GÛ©¿â$ñJ¾Æ&£;éQA·?E%èö	Ü>Û§¡Û'éö&êP	Üoï%ñ.½$ì}³Q>Û×!tûSTnÀí¹}º}no¢ÇíÙWÆÜû`â_0éöP¤GÝþ Û'pûDnn¤Û¨C%Ò·÷¨o¯¦±Á4JRA·?C%Ý>Û'rû<tû,ÝÞDJÜoï$ñ-©¨IîX¤C%£Û¢tûnÉíóÐí³t{u¨Dî·wx¨H·"UpûëËO¢J9èöÜ>Ûç¡Ûgéö&xoGX÷í½$ZqQÓØlÎöPdÃ|úË\^~gwÊA·ÏàöÜ>Ý>K·7Q£íÔ_ñ¨¿¢¦±ÉèEzTÒTnÁí3¹}º}no¢ÇíÄT¤ÛgéöP¤G%_A%èöÜ>Ûç¡Ûgéö&êPÜoï$ñîï,Ý^MrÇ"
ÂþþI%åß­rÐí3¸}&·ÏC·ÏÒíMÔ¡âh;W$Z3VÓØdtÇ"=*å
*A·ÏàöÜ>Ý>K·7QÊøÕõw7:ÄYº½QA·g*õ
*A·ÏàöÜ>Ý>K·7QJà9ù^÷í³t{5Éô¨´+¨Ý>Ûgrû<tû,ÝÞD*Îv{>V·ç+céö¶P¢nÏTúT Û/àöÜ~ºý"ÝÞDÊéÛ{IÔ··!Eöít{¢²Ü® tûÜ¥v=2éö&êPôí$ÞM¡¦±ÉèEzT¦+¨Ý~·_Èí¡Û/ÒíM=àë®D×`jò±nOøô'r{ýnÕ%èö¸ýBn¿Ý~no¢qKþî%ñJ¾Îöj;éQA·?E%èö¸ýBn¿Ý~no¢§%O«^­/ÂÞ7Ý±H
ºý)*A·_Àírûeèöt{u¨w÷xÍxn¯&¹ctûSTn¿Û/äöËÐíéö&êPqúöÔ!ö¨ClK!*rO>éQA·?E%èö¸ýBn¿Ý~no¢HßÞKb*ò~ûEÿEzTÐíOQ	ºýn¿Û/C·_¤Û¨C%Ò·wxç-¨H·"=*èö§¨Ý~·_Èí¡Û/ÒíMÔ¡2Öö»ÄçÑßlÁú
ºý*%èöÜ~!·/C·/ÒíM©§%Oé%Ñ5X}{5Ét¨tûSTn_Àí¹}º}no¢GÛi7Ä«¶¢"¥E6l? ÈTúë÷Û ÛpûBn_n_¤Û(®d¼aÝ·wxÅÅBT¤Ût{ºS¢ Û·R^¾S¢Ý¾Ûrû2tû"ÝÞD*¶Ó±DkÆEº½-¨ Û3tûSTn_Àí¹}º}no¢GÛéÌK¢5MFw,Ò£nJÐí¸}!·/C·/ÒíMÔ¡âh;í¦p¸ooK!*Òíº}&*èö}_¾S¢Ý¾Ûrû2tû"ÝÞD*÷Û{I¼óHMcB
º=SA·?E%èöÜ¾Û¡Ûéö&êPq´Ïö÷ÛÃ@DELrÇ"=*èö§¨Ý¾Ûrû2tû"ÝÞD*ãGàßÝ$>¯H·WÜ±H
ºý)*A·/àöÜ¾Ý¾H·7QJ¤oï$ñ.½":óîX¤GÝþtû
n_ÈíëÐí«t{e*5²'ßIâý`UöíUtÇ"*Ýþ ÛWpûJn_n_¥Û¨C%Ò·÷È"«°÷ÍFÉ"+º=SA·?E%èöÜ¾Û×¡ÛWéö&7-½aÝõòhuRMc³Q¦nO÷WpûZ~JÐí+¸}%·¯C·¯ÒíMÔ¡éÛ{IÔ_QÓØdtÇ"ûW*¸ý©ûWjÐí+¸}%·¯C·¯ÒíMÔ¡éÛ;I¼fl¢7}(+yH%_A%èöÜ¾Û×¡ÛWéö&êPqÜzN÷"Õ46e*ËÊr ÛWpûJn_n_¥Û¨CÅq{¦â¸=+Òí«ìÛCr ÛWpûJn_n_¥Û¨CÅq{Ztx^n¯&¹cz ÛWpûJn_n_¥Û¨CÅÑv¾2¼¯J·7Q>VÚJ»JÐí+¸}%·¯C·¯ÒíMÔ¡yÄ»)ªt{5Él¸Yñÿ¤RÓíåütûn_ÉíÛÐít{e*-ò|';Äf z>XnE:TÚí
*A·oàöÜ¾
Ý¾I·7Q£íd^Ydn¯&¹c
7`=àï§§A~|½ý«TnßÛ×ßCÜ@{{'*ÒíUôíêV¤DÆM¶íÕ,v¬±ãÒüý´|¼ÛúåÓJª}K t¥¥!©ö*úvDGD×ÅjMFw¬±ãÒüýJûË;\ZÐì[(d+-¡H³WÑ·#ªN_qøçKnÈ=(ù
(A±o@!YiË{};¢Ú $|öÍ;íoQ³Ø±FÊr ×·PÈUZB^¯¢oGÔ|ßÔðrx#gÑkô + µ¾UBªÒêÔz};¢ÚT¼$¾úOÈ·u:R¯´úÖ 
JBV¯¢oGT7ì$Ö¶or;ÖèAiW@	J}ë
ß<Üúz};¢º3ì$qg¸ÝöîX£¥_ ¥¾ß 
õ ûm¥K§WÑ·#ª[NË£­¡t©ôPcgy´U<¡ÔéuyìA¥ï@¡dP¤Ò«èÛÕë,N>üÖYL¨±ãÍ;¨búø`éùåu4úFÏw÷¡Ñwiô]öÛÕma/®¾ºhÇor;ÖØqÏþ~Zj=±¢¾ÑóÃ}hô]½ 8²Nû%$ÞgÆ!y4Q>RÒJºJÐè;=ß7ÜFß¥ÑwáÒoGToøöH»4ú.[õPcÇ=W¨ñ	¥=¡¾ÑómÃ}hô]½ 8FÏGDk÷j2e¹JÐè;=ß5ÜFß¥Ñw±ýýíªsøÝKâÅf£ !r Ñw0z¾i¸¾K£ïÂ¥ß¨îÓ{I´tß¥Ñ«è5zPêPFßÁèùá>4ú.¾öùÛÕ½$¾áNÍb³Qö6Ò®4úFÏ·÷¡Ñwiô]tÏß¨Z ¾{I¼_Íb³Ø±FJÿõP^òg  Ñ¿Å~B ÊZ¼$\Jþ`ÇÁ/9Çkd(ð÷g¡Äþ=Ï@A£?2eô0A	ì¿÷è.n;^Û(S°FÊtÑ¿ç(hôG¢ÞFñ%GTvÝ$\Ú~5vÜø§¥¥¥¾º o1£Ï3PÐèE½2@ÞMB£³Øl/±ÆÛðéO(9çW$ó-fôïy
ý¡ (£·QâôèÑSÜ$<ÑC%EÝX5zPòPbFÿg  Ñ
2ze(Nû/Ý$>§¨½ã5zP+ Äþ=Ï@A£?2eô6ÊPö;®{I´q*!(jë=ÖèA)W@ý{Fd((Êèm¡t÷¨ÉeÇá#E=
kô Ô+ Äþ=Ï@A£?2eô6ÊPÆÏ¹¿»Iì)jã½òFÏPÚPbFÿ÷)ºQøÈPPÑÛ(C	</ÏK¢m«r
ê$(hô¥_ e
ýFO÷	Ê$~Ýñ·#*÷{I´*A(ðýkt L·+ ~£§ÛEý$Lûíj£wh3TBP¤ÑOhôeºJÐè'0zºKøÈPP¤Ñ(¾zðÊÎ£ý;èÕw¬±7¼Aþþ	¥7Nä)hô=Ý$|d((Òè'áÒoGTnðhé*!(j×=ÖØ>{þ~Zú-·W{ôy
ýFO

In [39]:
df = pd.read_excel('data/laliga.xlsx')
df.head()

,Column1,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06-01,1,1,Atletico de Bilbao,Real Sociedad,3,0,2005-08-27,1125093600
1,26202,2005-06-01,1,1,Alaves,Barcelona,0,0,2005-08-27,1125093600
2,26203,2005-06-01,1,1,Valencia,Betis,1,0,2005-08-27,1125093600
3,26204,2005-06-01,1,1,Atletico de Madrid,Zaragoza,0,0,2005-08-28,1125180000
4,26205,2005-06-01,1,1,Cadiz,Real Madrid,1,2,2005-08-28,1125180000

No tenemos problemas cuando los datos están perfectos, con una única hoja, y empezando en la celda A1. ¿Qué argumentos nos pueden resultar útiles?

1. `io`: dónde está el archivo
2. `sheet_name`: el nombre de la hoja
3. `header`: dónde está la cabecera
4. `usecols`: indica el rango de columnas Excel en el que se encuentran. Por ejemplo: 'A:F'
5. `skiprows`: filas que deberia ignorar

Veamos más ejemplos. El Excel de `laliga.xlsx` tiene varias pestañas. Por defecto, lee la primera, `Hoja1`, pero podemos especificar otras.

In [40]:
df = pd.read_excel('data/laliga.xlsx', sheet_name = 'Hoja2')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Column1,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
2,26201,2005-06-01 00:00:00,1,1,Atletico de Bilbao,Real Sociedad,3,0,2005-08-27 00:00:00,1125093600
3,26202,2005-06-01 00:00:00,1,1,Alaves,Barcelona,0,0,2005-08-27 00:00:00,1125093600
4,26203,2005-06-01 00:00:00,1,1,Valencia,Betis,1,0,2005-08-27 00:00:00,1125093600

Vemos que hay algún problema con los datos. Las primeras líneas están en blanco en el Excel. Podemos, o bien ignorarlas, o indicarle donde está la cabecera

In [41]:
df = pd.read_excel('data/laliga.xlsx', sheet_name = 'Hoja2', header = 2)
df.head()

,Column1,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06-01,1,1,Atletico de Bilbao,Real Sociedad,3,0,2005-08-27,1125093600
1,26202,2005-06-01,1,1,Alaves,Barcelona,0,0,2005-08-27,1125093600
2,26203,2005-06-01,1,1,Valencia,Betis,1,0,2005-08-27,1125093600
3,26204,2005-06-01,1,1,Atletico de Madrid,Zaragoza,0,0,2005-08-28,1125180000
4,26205,2005-06-01,1,1,Cadiz,Real Madrid,1,2,2005-08-28,1125180000

Otro problema que nos puede surgir es que la tabla no esté ni en las primeas filas, ni en las primeras columnas

In [42]:
df = pd.read_excel('data/laliga.xlsx',
                   sheet_name = 'Hoja3',
                  header = 2,
                  usecols = 'B:K')
df.head()

,Column1,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06-01,1,1,Atletico de Bilbao,Real Sociedad,3,0,2005-08-27,1125093600
1,26202,2005-06-01,1,1,Alaves,Barcelona,0,0,2005-08-27,1125093600
2,26203,2005-06-01,1,1,Valencia,Betis,1,0,2005-08-27,1125093600
3,26204,2005-06-01,1,1,Atletico de Madrid,Zaragoza,0,0,2005-08-28,1125180000
4,26205,2005-06-01,1,1,Cadiz,Real Madrid,1,2,2005-08-28,1125180000

In [43]:
df = pd.read_excel('data/laliga.xlsx',
                   sheet_name = 'Hoja4',
                  header = 3,
                  usecols = 'C:L',
                  nrows = 7)
df.head(50)

,Column1,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06-01,1,1,Atletico de Bilbao,Real Sociedad,3,0,2005-08-27,1125093600
1,26202,2005-06-01,1,1,Alaves,Barcelona,0,0,2005-08-27,1125093600
2,26203,2005-06-01,1,1,Valencia,Betis,1,0,2005-08-27,1125093600
3,26204,2005-06-01,1,1,Atletico de Madrid,Zaragoza,0,0,2005-08-28,1125180000
4,26205,2005-06-01,1,1,Cadiz,Real Madrid,1,2,2005-08-28,1125180000
5,26206,2005-06-01,1,1,Celta de Vigo,Malaga,2,0,2005-08-28,1125180000
6,26207,2005-06-01,1,1,Espanol,Getafe,0,2,2005-08-28,1125180000

In [44]:
df = pd.read_excel('data/laliga.xlsx',
                   sheet_name = 'Hoja5',
                   skiprows=list(range(4942,4952)))
len(df)

4964

In [45]:
df = pd.read_excel('data/laliga.xlsx',
                   sheet_name = 'Hoja5')
len(df)
df.iloc[4940:4955]

,Column1,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
4940,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4941,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4942,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4943,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4944,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4945,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4946,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4947,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4948,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4949,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4950,36661.0,NaT,1.0,36.0,Atletico de Madrid,Espanol,0.0,2.0,2018-05-06,1.525558e+09
4951,36662.0,NaT,1.0,36.0,Malaga,Alaves,0.0,3.0,2018-05-06,1.525558e+09
4952,36663.0,NaT,1.0,36.0,Barcelona,Real Madrid,2.0,2.0,2018-05-06,1.525558e+09
4953,36664.0,NaT,1.0,36.0,Leganes,Levante,0.0,3.0,2018-05-07,1.525644e+09
4954,36665.0,NaT,1.0,37.0,Girona,Valencia,0.0,1.0,2018-05-12,1.526076e+09

In [46]:
len(range(4942,4952))

10

**Escritura de Excel**

Al igual que con el CSV, tenemos el método `to_excel()`, para escribir el `DataFame` en un archivo Excel. **Recuerda poner la extensión del Excel (.xlsx) en el nombre del archivo**. Tienes [el enlace a la documentación para ver más detalle](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html).

In [47]:
df.to_excel('data/laligaExcelWrite.xlsx')

## 5. JSON
***JavaScript Objet Notation* es otro formato de texto plano que se utiliza para el intercambio de datos**. Originalmente se utilizaba como notación literal de objetos en JavaScript, pero actualmente es un formato de datos independiente del lenguaje. JavaScript es un lenguaje de programación web, por lo que JSON se utiliza mucho en el intercambio de objetos entre cliente y servidor.

**¿Qué diferencia hay con un CSV o un Excel?** Ya no tenemos esa estructura de fila/columna, sino que ahora es un formato tipo clave/valor, como si fuese un diccionario. En una tabla en la fila 1, columna 1, tienes un valor. En un JSON no, en la clave "mi_clave" puedes tener almacenado un valor, una lista o incluso un objeto. Salimos del formato tabla al que estamos acostubrados para ganar en flexibilidad.

Un JSON tiene la siguiente pinta:

![imagen](./img/json_image.png)

In [48]:
data1 =  {
        "firstName": "Jane",
        "lastName": "Doooooo"
}
data2 =  {
        "firstName": "Joe",
        "lastName": "Doe"
}
data3 =  {
        "firstName": "J",
        "lastName": "D"
}
df = pd.DataFrame([data1,data2,data3])
df

  firstName lastName
0      Jane  Doooooo
1       Joe      Doe
2         J        D

In [49]:
dictionario = { "Col1": [1,2,3,4,5], "Col2": [6,5,7,8,9]}
df = pd.DataFrame(dictionario)
df

   Col1  Col2
0     1     6
1     2     5
2     3     7
3     4     8
4     5     9

In [50]:
data =  {
        "firstName": "Jane",
        "lastName": "Doe",
        "hobbies": ["running", "sky diving", "singing"],
        "age": 35,
        "children": [
            {
                "firstName": "Alice",
                "age": 6
            },
            {
                "firstName": "Bob",
                "age": 8
            }
        ]
    }

In [51]:
data['hobbies']

['running', 'sky diving', 'singing']

In [52]:
data['hobbies'][0]

'running'

In [53]:
data['children'][1]['firstName']

'Bob'

In [54]:
for kid in data['children']:
    print(kid['firstName'])

Alice
Bob

**Puedo guardar el JSON en un archivo. Para ello, usamos la librería `json`**, que viene incluida en la instalación de Anaconda.

In [55]:
import json

with open("data/data_file.json", "w") as write_file:
    json.dump(data, write_file) # Le da la estructura json

O también objetos de una clase

In [56]:
class Persona:
    piernas = 2
    def __init__(self, firstName, lastName, hobbies):
        self.firstName = firstName
        self.lastName = lastName
        self.hobbies = hobbies
        
pers1 = Persona("Pepe", "Carrasco", ["Bricolaje", "Tenis"])
pers2 = Persona("Jose", "Carrasco", ["Bricolaje", "Tenis"])

In [57]:
type(pers1)

__main__.Persona

In [58]:
pers1.__dict__

{'firstName': 'Pepe',
 'lastName': 'Carrasco',
 'hobbies': ['Bricolaje', 'Tenis']}

Lo puedo guardar en un archivo *pepe.json*

In [59]:
with open("data/pepe.json", "w") as write_file:
    json.dump(pers2.__dict__, write_file)

Luego lo puedo volver a cargar

In [60]:
with open("data/pepe.json", "r") as json_file:
    data = json.load(json_file)
    
print(data)
print(data['firstName'])

{'firstName': 'Jose', 'lastName': 'Carrasco', 'hobbies': ['Bricolaje', 'Tenis']}
Jose

Para el siguiente ejemplo, utilizamos `pandas` y leeremos el archivo JSON, de tal manera que nos transforme los datos en formato tabla, en un `DataFrame`.

In [61]:
df_json = pd.read_json('data/Musical_Instruments_5.json',lines=True) # lines:True --> consiferar cada línea un objeto json
df_json

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A2IBPI20UZIR0U,1384719342,"cassandra tu ""Yeah, well, that's just like, u...","[0, 0]","Not much to write about here, but it does exac...",5,good,1393545600,"02 28, 2014"
1,A14VAT5EAX3D9S,1384719342,Jake,"[13, 14]",The product does exactly as it should and is q...,5,Jake,1363392000,"03 16, 2013"
2,A195EZSQDW3E21,1384719342,"Rick Bennette ""Rick Bennette""","[1, 1]",The primary job of this device is to block the...,5,It Does The Job Well,1377648000,"08 28, 2013"
3,A2C00NNG1ZQQG2,1384719342,"RustyBill ""Sunday Rocker""","[0, 0]",Nice windscreen protects my MXL mic and preven...,5,GOOD WINDSCREEN FOR THE MONEY,1392336000,"02 14, 2014"
4,A94QU4C90B1AX,1384719342,SEAN MASLANKA,"[0, 0]",This pop filter is great. It looks and perform...,5,No more pops when I record my vocals.,1392940800,"02 21, 2014"
...,...,...,...,...,...,...,...,...,...
10256,A14B2YH83ZXMPP,B00JBIVXGC,Lonnie M. Adams,"[0, 0]","Great, just as expected. Thank to all.",5,Five Stars,1405814400,"07 20, 2014"
10257,A1RPTVW5VEOSI,B00JBIVXGC,Michael J. Edelman,"[0, 0]",I've been thinking about trying the Nanoweb st...,5,"Long life, and for some players, a good econom...",1404259200,"07 2, 2014"
10258,AWCJ12KBO5VII,B00JBIVXGC,Michael L. Knapp,"[0, 0]",I have tried coated strings in the past ( incl...,4,Good for coated.,1405987200,"07 22, 2014"
10259,A2Z7S8B5U4PAKJ,B00JBIVXGC,"Rick Langdon ""Scriptor""","[0, 0]","Well, MADE by Elixir and DEVELOPED with Taylor...",4,Taylor Made,1404172800,"07 1, 2014"
10260,A2WA8TDCTGUADI,B00JBIVXGC,TheTerrorBeyond,"[0, 0]","These strings are really quite good, but I wou...",4,"These strings are really quite good, but I wou...",1405468800,"07 16, 2014"

## 6. TXT
**Son simplemente archivos donde hay texto**. Hemos visto que los CSVs y los JSON tienen su propio formato y extension. En el caso del .txt no tienen ninguno específico aunque no quita para que sus elementos estén separados por comas, y se pueda leer igualmente como si fuese un CSV.

Cuando almacenamos datos siempre tienen una estructura, por lo que aunque sea un `.txt`, llevará los datos en formato json, separados por comas, tabulaciones, puntos y comas...

Por ejemplo, si tenemos los datos de la liga guardados en un `.txt`, separados por tabulaciones, lo podremos leer con el `pd.read_csv()`.

In [62]:
df = pd.read_csv('data/laligaTXT.txt', sep='\t')
df.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

Recuerda que la separación por tabulaciones, también tiene su propia extensión: el `.tsv`, que igualmente lo podremos leer con `read_csv()`.

In [63]:
df = pd.read_csv('data/laligaTSV.tsv', sep='\t')
df.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

El método `read_csv()` no se ciñe únicamente a leer CSVs, sino a prácticamente cualquier archivo que lleve un carácter concreto en la separación de sus campos. Si conocemos ese caracter, sabremos leer el archivo con `pandas`.

## 7. ZIP
En ocasiones los datos que recibimos en nuestros programas están comprimidos, ya sea en un formato `.zip`, `.rar`, `.7z`, u otro tipo de archivo.

En este apartado verás un ejemplo de cómo descomprimir archivos `.zip`. Para ello empleamos la librería `zipfile` que viene incluida en la instalación de Anaconda. [Tienes el enlace a la documentación para más detalle](https://docs.python.org/3/library/zipfile.html#zipfile-objects).

Para extraer todos los archivos:

In [64]:
import zipfile

with zipfile.ZipFile('data/laligaZIP.zip') as zip_ref:
    data_zip = zip_ref.extractall('data')

Si quieres descomprimir un archivo `.rar` [tendrás que descargarte un paquete como por ejemplo `unrar`.](https://pypi.org/project/unrar/)

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio zip</h3>

Consulta la documentación para extrar un único archivo por nombre de data/laligaZIP.zip en la carpeta extracted_files.
         
 </td></tr>
</table>

In [66]:
with zipfile.ZipFile('data/laligaZIP.zip') as zip_ref:
    zip_ref.extract('laligaZIP.csv','extracted_files')

## 8. pickle
**`pickle` es el módulo que nos permite serializar y deserializar un objeto de Python**. Esta operación lo que hace es traducirlo a un stream de bytes.

A efectos prácticos, lo que nos permite es guardar objetos de Python, y recuperarlos más adelante.

In [67]:
pers1

In [68]:
import pickle

df = pd.read_csv("data/laliga.csv")

with open('data/pepe.json') as json_file:
    data = json.load(json_file)
    
with open('data/importante.pkl', 'wb') as f:
    pickle.dump(pers1, f)
    pickle.dump(df, f)
    pickle.dump(data, f)

In [69]:
with open('data/importante.pkl', 'rb') as f:
    a = pickle.load(f)
    b = pickle.load(f)
    c = pickle.load(f)
    
#print(a)
print(type(b))
print(b)
print(c)

<class 'pandas.DataFrame'>
      Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0          26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad
1          26202  2005-06         1      1              Alaves      Barcelona
2          26203  2005-06         1      1            Valencia          Betis
3          26204  2005-06         1      1  Atletico de Madrid       Zaragoza
4          26205  2005-06         1      1               Cadiz    Real Madrid
...          ...      ...       ...    ...                 ...            ...
4935       36680  2017-18         1     38          Villarreal    Real Madrid
4936       36681  2017-18         1     38  Atletico de Bilbao        Espanol
4937       36682  2017-18         1     38           Barcelona  Real Sociedad
4938       36683  2017-18         1     38            Valencia      Deportivo
4939       36684  2017-18         1     38  Atletico de Madrid          Eibar

      localGoals  visitorGoals        date   timestamp
0              3             0  27/08/2005  1125093600
1              0             0  27/08/2005  1125093600
2              1             0  27/08/2005  1125093600
3              0             0  28/08/2005  1125180000
4              1             2  28/08/2005  1125180000
...          ...           ...         ...         ...
4935           2             2  19/05/2018  1526680800
4936           0             1  20/05/2018  1526767200
4937           1             0  20/05/2018  1526767200
4938           2             1  20/05/2018  1526767200
4939           2             2  20/05/2018  1526767200

[4940 rows x 10 columns]
{'firstName': 'Jose', 'lastName': 'Carrasco', 'hobbies': ['Bricolaje', 'Tenis']}

In [70]:
print(type(a))
a.firstName

<class '__main__.Persona'>

'Pepe'

In [71]:
b.head()

,Unnamed: 0,season,division,round,localTeam,visitorTeam,localGoals,visitorGoals,date,timestamp
0,26201,2005-06,1,1,Atletico de Bilbao,Real Sociedad,3,0,27/08/2005,1125093600
1,26202,2005-06,1,1,Alaves,Barcelona,0,0,27/08/2005,1125093600
2,26203,2005-06,1,1,Valencia,Betis,1,0,27/08/2005,1125093600
3,26204,2005-06,1,1,Atletico de Madrid,Zaragoza,0,0,28/08/2005,1125180000
4,26205,2005-06,1,1,Cadiz,Real Madrid,1,2,28/08/2005,1125180000

In [72]:
c

{'firstName': 'Jose',
 'lastName': 'Carrasco',
 'hobbies': ['Bricolaje', 'Tenis']}

## 9. Encoding

In [73]:
pd.read_csv('data/encoding.csv', encoding = 'utf-8')

      País                       Comida
0   España                       paella
1    Japón                        sushi
2  Francia  La Lamproie à la Bordelaise

In [74]:
pd.read_csv('data/encoding.csv', encoding = 'iso-8859-1')

     PaÃ­s                        Comida
0  EspaÃ±a                        paella
1   JapÃ³n                         sushi
2  Francia  La Lamproie Ã  la Bordelaise

In [75]:
pd.read_csv('data/encoding.csv')

      País                       Comida
0   España                       paella
1    Japón                        sushi
2  Francia  La Lamproie à la Bordelaise

In [76]:
pd.read_csv('data/encoding.csv', encoding = 'ascii')

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

In [77]:
pd.read_csv('data/encoding.csv', encoding='iso8859_10')

     PaÃ­s                        Comida
0  EspaÃąa                        paella
1   JapÃģn                         sushi
2  Francia  La Lamproie Ã  la Bordelaise

In [78]:
pd.read_csv('data/encoding.csv')

      País                       Comida
0   España                       paella
1    Japón                        sushi
2  Francia  La Lamproie à la Bordelaise

## 10. Archivos y carpetas
Resulta de gran utilidad automatizar lecturas/escrituras/borrado/movimientos de archivos entre carpetas. Si tenemos un proceso definido en Python, podremos ejecutarlo tantas veces queramos y de este modo evitar dedicarle tiempo tareas tediosas y rutinarias. Para ello tendremos que apoyarnos en el módulo de Python `os`.

Lo primero de todo es saber en qué directorio estamos trabajando. Esto es fundamental para elegir bien la ruta relativa.

In [79]:
import os
os.getcwd()

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría'

In [80]:
import shutil

El directorio de trabajo lo podríamos cambiar si quisiéramos, por ejemplo, al escritorio.

In [81]:
os.chdir('*+*+_Mi_ruta_absoluta_al_escritorio_+*+*')
print(os.getcwd())
print(os.listdir())

OSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: '*+*+_Mi_ruta_absoluta_al_escritorio_+*+*'

Podemos juntar rutas en un único path. Realiza un concatenado con barras entendibles por Windows.

In [82]:
os.path.join("C:\\path\\directory", "some_file.txt")

'C:\\path\\directory\\some_file.txt'

Si quieres buscar algún tipo de archivo concreto, tienes varias opciones:
- Buscar por nombre
- Buscar por extensión

En función de lo que encuentres, realizarás una operación u otra. Ahora bien, igualmente para buscar, tendrás que recorrer todos los archivos que estén en un directorio o en varios directorios. Para listar todos los ARCHIVOS y CARPETAS que hay en el directorio actual de trabajo, utilizamos `os.listdir()`.

In [83]:
os.getcwd()

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría'

In [84]:
os.listdir()

['data',
 'extracted_files',
 'img',
 'Lectura_Escritura.ipynb',
 'print_os_getcwd.py']

Voy a quedarme con todos los notebooks del actual directorio de trabajo.

In [85]:
for i in os.listdir():
    if i.endswith('.ipynb'):
        print("Notebook", i)

Notebook Lectura_Escritura.ipynb

Si quiero acceder sólo a los directorios

In [86]:
for i in os.listdir():
    if '.' not in i:
        print("directorio", i)

directorio data
directorio extracted_files
directorio img

Otro método interesante para bucear en los archivos y carpetas de un directorio concreto es el `os.walk()`. Va a devolver un iterable que podremos recorrer en un for y obtener en formato tupla todos los archivos, subcarpetas y ficheros de subcarpetas. Para cada elemento de la tupla tenemos:
- El directorio donde está apuntando.
- Los directorios que hay ahí.
- Los archivos que hay ahí.

In [87]:
result_generator = os.walk(os.getcwd())

files_result = [x for x in result_generator]
files_result

[('c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría',
  ['data', 'extracted_files', 'img'],
  ['Lectura_Escritura.ipynb', 'print_os_getcwd.py']),
 ('c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\data',
  [],
  ['class_hlf.py',
   'class_hlf.txt',
   'data_file.json',
   'dog_breeds.txt',
   'dummy.csv',
   'ejercicio.csv',
   'ejercicio_clase.csv',
   'encoding.csv',
   'file_write.txt',
   'file_writes.txt',
   'importante.pkl',
   'laliga.csv',
   'laliga.xlsx',
   'laliga4.csv',
   'laligaExcelWrite.xlsx',
   'laligaPC.csv',
   'laligaTSV.tsv',
   'laligaTXT.txt',
   'laligaWrite.csv',
   'laligaZIP.csv',
   'laligaZIP.zip',
   'Musical_Instruments_5.json',
   'pepe.json',
   'poblacion.csv',
   'preguntas.py']),
 ('c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\extracted_files',
  [],
  ['laligaZIP.csv']),
 ('c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\img',
  [],
  ['ejercicio.png',
   'ejercicios.png',
   'encoding.jpg',
   'error.png',
   'file.png',
   'importante',
   'json_image.png',
   'path.png',
   'python.jpg',
   'python.png'])]

¿Qué podemos hacer dentro de un directorio, aparte de listar ficheros y subdirectorios? Las principales operaciones serían:
- Crear o eliminar directorios
- Crear o eliminar ficheros
- Mover ficheros

In [88]:
os.getcwd()

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría'

In [90]:
os.listdir("c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría")

['data',
 'extracted_files',
 'img',
 'Lectura_Escritura.ipynb',
 'print_os_getcwd.py']

In [91]:
os.mkdir('direct_prueba')

FileExistsError: [Errno 17] File exists: 'direct_prueba'

In [92]:
os.rmdir('direct_prueba')

In [93]:
f = open("fichero.txt", "w")

for i in range(10):
    f.write("Line:" + str(i)+ "\n")
    
f.close()

In [94]:
import shutil
shutil.move("fichero.txt", "fichero2.txt")

'fichero2.txt'

In [95]:
shutil.move("fichero2.txt", "extracted_files/")

'extracted_files/fichero2.txt'

In [96]:
os.remove('extracted_files/fichero2.txt')

In [97]:
os.path.abspath('data/fichero.txt')

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\data\\fichero.txt'

In [98]:
os.path.dirname(os.path.abspath('data/fichero.txt'))

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\data'

In [99]:
os.getcwd()

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría'

In [100]:
os.path.abspath('extracted_files/laligaZIP.csv')

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\extracted_files\\laligaZIP.csv'

In [101]:
os.path.dirname(os.path.abspath('extracted_files/laligaZIP.csv'))

'c:\\Users\\urkow\\Documents\\Documentos_Clase\\2026-02-BILBAO-FT-Data-Science\\2-Data_Analysis\\3-Sources\\Archivos\\Teoría\\extracted_files'