# Ejercicios ensembling
En este ejercicio vas a realizar prediciones sobre un dataset de ciudadanos indios diabéticos. Se trata de un problema de clasificación en el que intentaremos predecir 1 (diabético) 0 (no diabético).

### 1. Carga las librerias que consideres comunes al notebook

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

### 2. Lee los datos de [esta direccion](https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv)
Los nombres de columnas son:
```Python
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
```

In [2]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

df = pd.read_csv(url)
df.columns = names
df.head()

   preg  plas  pres  skin  test  mass   pedi  age  class
0     1    85    66    29     0  26.6  0.351   31      0
1     8   183    64     0     0  23.3  0.672   32      1
2     1    89    66    23    94  28.1  0.167   21      0
3     0   137    40    35   168  43.1  2.288   33      1
4     5   116    74     0     0  25.6  0.201   30      0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   preg    767 non-null    int64
 1   plas    767 non-null    int64
 2   pres    767 non-null    int64
 3   skin    767 non-null    int64
 4   test    767 non-null    int64
 5   mass    767 non-null    float64
 6   pedi    767 non-null    float64
 7   age     767 non-null    int64
 8   class   767 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
preg,767.0,3.842243,3.370877,0.000,1.0000,3.000,6.000,17.00
plas,767.0,120.859192,31.978468,0.000,99.0000,117.000,140.000,199.00
pres,767.0,69.101695,19.368155,0.000,62.0000,72.000,80.000,122.00
skin,767.0,20.517601,15.954059,0.000,0.0000,23.000,32.000,99.00
test,767.0,79.903520,115.283105,0.000,0.0000,32.000,127.500,846.00
mass,767.0,31.990482,7.889091,0.000,27.3000,32.000,36.600,67.10
pedi,767.0,0.471674,0.331497,0.078,0.2435,0.371,0.625,2.42
age,767.0,33.219035,11.752296,21.000,24.0000,29.000,41.000,81.00
class,767.0,0.348110,0.476682,0.000,0.0000,0.000,1.000,1.00

In [5]:
df['class'].value_counts()

class
0    500
1    267
Name: count, dtype: int64

### 3. Bagging
Para este apartado tendrás que crear un ensemble utilizando la técnica de bagging ([BaggingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html)), mediante la cual combinarás 100 [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html). Recuerda utilizar también [cross validation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html) con 10 kfolds.

**Para este apartado y siguientes, no hace falta que dividas en train/test**, por hacerlo más sencillo. Simplemente divide tus datos en features y target.

Establece una semilla

In [6]:
# Sospecho que el objetivo es calcular class, que nos indica si el paciente es diabético o no.
X = df[['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age']]
y = df['class']

print(X.shape)
print(y.shape)
# No definimos train/test

(767, 8)
(767,)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

estimator = DecisionTreeClassifier(max_depth=3,random_state=42)

bag_clf = BaggingClassifier(
    estimator = estimator,
    n_estimators=100, # Cantidad de árboles
    max_samples=100, # Muestras utilizadas en bootstrapping
    bootstrap=True, # Usamos bootstrapping: muestreo con reemplazo.
    max_features = 3, # Features que utiliza en el bootstrapping. Cuanto más bajo, mejor generalizará y menos overfitting
    random_state=42)


bag_clf.fit(X, y)

BaggingClassifier(estimator=DecisionTreeClassifier(max_depth=3,
                                                   random_state=42),
                  max_features=3, max_samples=100, n_estimators=100,
                  random_state=42)

In [14]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(bag_clf, X, y, cv=10)
print(scores)
print(scores.mean())

[0.72727273 0.76623377 0.76623377 0.71428571 0.72727273 0.76623377
 0.77922078 0.72368421 0.69736842 0.81578947]
0.7483595352016404

In [8]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = bag_clf.predict(X)

print('Accuracy:', accuracy_score(y, y_pred))
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

Accuracy: 0.7770534550195567
[[477  23]
 [148 119]]
              precision    recall  f1-score   support

           0       0.76      0.95      0.85       500
           1       0.84      0.45      0.58       267

    accuracy                           0.78       767
   macro avg       0.80      0.70      0.71       767
weighted avg       0.79      0.78      0.76       767

In [9]:
# Guardamos resultados, para siguiente ejercicio. Definimos función
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def evaluar_modelo(nombre, modelo, X_test, y_test):
    y_pred = modelo.predict(X_test)
    y_prob = modelo.predict_proba(X_test)[:, 1]

    return {
        'modelo': nombre,
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred),
        'recall': recall_score(y_test, y_pred),
        'f1': f1_score(y_test, y_pred),
        'auc': roc_auc_score(y_test, y_prob)
    }

In [10]:
# Guardamos nuestro resultado de 'Bagging'
resultados = []
resultados.append(evaluar_modelo('Bagging', bag_clf, X, y))

### 4. Random Forest
En este caso entrena un [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) con 100 árboles y un `max_features` de 3. También con validación cruzada

In [11]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(
    n_estimators=100,
    max_leaf_nodes=16,
    max_features=3,
    random_state=42)

rnd_clf.fit(X, y)

RandomForestClassifier(max_features=3, max_leaf_nodes=16, random_state=42)

In [13]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rnd_clf, X, y, cv=10)
print(scores)
print(scores.mean())

[0.76623377 0.80519481 0.79220779 0.67532468 0.7012987  0.81818182
 0.79220779 0.84210526 0.72368421 0.80263158]
0.771907040328093

In [16]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = rnd_clf.predict(X)

print('Accuracy:', accuracy_score(y, y_pred))
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

Accuracy: 0.8396349413298566
[[464  36]
 [ 87 180]]
              precision    recall  f1-score   support

           0       0.84      0.93      0.88       500
           1       0.83      0.67      0.75       267

    accuracy                           0.84       767
   macro avg       0.84      0.80      0.81       767
weighted avg       0.84      0.84      0.84       767

In [17]:
# Guardamos nuestro resultado de 'Random Forest'
resultados.append(evaluar_modelo('Random Forest', rnd_clf, X, y))

### 5. AdaBoost
Implementa un [AdaBoostClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html) con 30 árboles.

In [18]:
from sklearn.ensemble import AdaBoostClassifier

estimator = DecisionTreeClassifier(max_depth=2)

ada_clf = AdaBoostClassifier(estimator = estimator,
                             n_estimators=30,
                             learning_rate=0.5,
                             random_state=42)

ada_clf.fit(X, y)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
                   learning_rate=0.5, n_estimators=30, random_state=42)

In [19]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(ada_clf, X, y, cv=10)
print(scores)
print(scores.mean())

[0.71428571 0.81818182 0.72727273 0.64935065 0.68831169 0.75324675
 0.80519481 0.80263158 0.72368421 0.80263158]
0.7484791524265209

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = ada_clf.predict(X)

print('Accuracy:', accuracy_score(y, y_pred))
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

Accuracy: 0.8070404172099087
[[451  49]
 [ 99 168]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       500
           1       0.77      0.63      0.69       267

    accuracy                           0.81       767
   macro avg       0.80      0.77      0.78       767
weighted avg       0.80      0.81      0.80       767

In [21]:
# Guardamos nuestro resultado de 'AdaBoost'
resultados.append(evaluar_modelo('AdaBoost', ada_clf, X, y))

### 6. GradientBoosting
Implementa un [GradientBoostingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html) con 100 estimadores

In [22]:
from sklearn.ensemble import GradientBoostingClassifier

grb_clf = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=3,
    min_samples_split=5,
    min_samples_leaf=2,
    subsample=0.8,
    loss='log_loss',
    random_state=42)

grb_clf.fit(X, y)

GradientBoostingClassifier(learning_rate=0.05, min_samples_leaf=2,
                           min_samples_split=5, random_state=42, subsample=0.8)

In [23]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(grb_clf, X, y, cv=10)
print(scores)
print(scores.mean())

[0.74025974 0.80519481 0.76623377 0.63636364 0.74025974 0.77922078
 0.80519481 0.84210526 0.71052632 0.78947368]
0.7614832535885168

In [24]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = grb_clf.predict(X)

print('Accuracy:', accuracy_score(y, y_pred))
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

Accuracy: 0.8604954367666232
[[462  38]
 [ 69 198]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.90       500
           1       0.84      0.74      0.79       267

    accuracy                           0.86       767
   macro avg       0.85      0.83      0.84       767
weighted avg       0.86      0.86      0.86       767

In [25]:
# Guardamos nuestro resultado de 'GradientBoost'
resultados.append(evaluar_modelo('GradientBoost', grb_clf, X, y))

### 7. XGBoost
Para este apartado utiliza un [XGBoostClassifier](https://docs.getml.com/latest/api/getml.predictors.XGBoostClassifier.html) con 100 estimadores. XGBoost no forma parte de la suite de modelos de sklearn, por lo que tendrás que instalarlo con pip install

In [26]:
import xgboost

xgb_clf = xgboost.XGBClassifier(
    n_estimators=100,
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42)

xgb_clf.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [27]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(xgb_clf, X, y, cv=10)
print(scores)
print(scores.mean())

[0.71428571 0.77922078 0.68831169 0.66233766 0.67532468 0.75324675
 0.77922078 0.78947368 0.71052632 0.78947368]
0.7341421736158578

In [28]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = xgb_clf.predict(X)

print('Accuracy:', accuracy_score(y, y_pred))
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

Accuracy: 1.0
[[500   0]
 [  0 267]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       500
           1       1.00      1.00      1.00       267

    accuracy                           1.00       767
   macro avg       1.00      1.00      1.00       767
weighted avg       1.00      1.00      1.00       767

Tan poderoso es este método que si usamos todos los datos se ajusta perfectamente???

In [29]:
# Guardamos nuestro resultado de 'XGBoost'
resultados.append(evaluar_modelo('XGBoost', xgb_clf, X, y))

### 8. Primeros resultados
Crea un dataframe con los resultados y sus algoritmos, ordenándolos de mayor a menor

In [30]:
# Con los resultados guardados, montamos df
df_result = pd.DataFrame(resultados)
df_result = df_result.sort_values(by='accuracy', ascending=False)
df_result

          modelo  accuracy  precision    recall        f1       auc
4        XGBoost  1.000000   1.000000  1.000000  1.000000  1.000000
3  GradientBoost  0.860495   0.838983  0.741573  0.787276  0.937393
1  Random Forest  0.839635   0.833333  0.674157  0.745342  0.920240
2       AdaBoost  0.807040   0.774194  0.629213  0.694215  0.888985
0        Bagging  0.777053   0.838028  0.445693  0.581907  0.868397

### 9. Hiperparametrización
Vuelve a entrenar los modelos de nuevo, pero esta vez dividiendo el conjunto de datos en train/test y utilizando un gridsearch para encontrar los mejores hiperparámetros.

In [31]:
# Sospecho que el objetivo es calcular class, que nos indica si el paciente es diabético o no.
X = df[['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age']]
y = df['class']

print(X.shape)
print(y.shape)

(767, 8)
(767,)

Separamos train/test en 80-20%

In [32]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['class'])
y = df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(613, 8)
(154, 8)
(613,)
(154,)

##### Bagging

Cross validation

In [33]:
from sklearn.model_selection import GridSearchCV, KFold

base_tree = DecisionTreeClassifier(random_state=42)

bag = BaggingClassifier(
    estimator=base_tree,
    n_estimators=100,
    random_state=42,
    n_jobs=-1)

param_grid = {
    'max_samples': [50, 60, 70],
    'max_features': [2, 3, 4],
    'bootstrap': [True],
    'estimator__max_depth': [3, 4, 5]}

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

grid = GridSearchCV(
    estimator=bag,
    param_grid=param_grid,
    cv=kfold,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train, y_train)

print('Mejores hiperparámetros:', grid.best_params_)
print('Mejor score CV:', grid.best_score_)

Mejores hiperparámetros: {'bootstrap': True, 'estimator__max_depth': 4, 'max_features': 4, 'max_samples': 70}
Mejor score CV: 0.7537017451084081

Hemos validado nuestro modelo. Ahora construimos y entrenamos el modelo definitivo.

In [34]:
estimator = DecisionTreeClassifier(max_depth=5, random_state=42)

# Modelo definitivo
bag_final = BaggingClassifier(
    estimator=estimator,
    n_estimators=100,
    max_samples=70,
    bootstrap=True,
    max_features=4,
    random_state=42,
    n_jobs=-1)

bag_final.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(max_depth=5,
                                                   random_state=42),
                  max_features=4, max_samples=70, n_estimators=100, n_jobs=-1,
                  random_state=42)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred_final = bag_final.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_final))
print(confusion_matrix(y_test, y_pred_final))
print(classification_report(y_test, y_pred_final))

Accuracy: 0.7727272727272727
[[89  8]
 [27 30]]
              precision    recall  f1-score   support

           0       0.77      0.92      0.84        97
           1       0.79      0.53      0.63        57

    accuracy                           0.77       154
   macro avg       0.78      0.72      0.73       154
weighted avg       0.78      0.77      0.76       154

In [36]:
# Guardamos resultado
resultados_cv = []
resultados_cv.append(evaluar_modelo('Bagging', bag_final, X_test, y_test))

##### Random Forest

Cross validation

In [ ]:
from sklearn.model_selection import GridSearchCV, KFold

forest = RandomForestClassifier(n_estimators=100,random_state=42)

param_grid = {
    'max_depth': [3, 5, 10],
    'max_leaf_nodes': [12, 16, 20],
    'min_samples_split': [3, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [2, 3, 4],
    'bootstrap': [True]}

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

grid = GridSearchCV(
    estimator=forest,
    param_grid=param_grid,
    cv=kfold,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train, y_train)

print('Mejores hiperparámetros:', grid.best_params_)
print('Mejor score CV:', grid.best_score_)

Mejores hiperparámetros: {'bootstrap': True, 'max_depth': 5, 'max_features': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'min_samples_split': 2}
Mejor score CV: 0.7716287678476996

Ahora construimos y entrenamos el modelo definitivo.

In [38]:
from sklearn.tree import DecisionTreeClassifier

# Modelo definitivo
for_final = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    max_leaf_nodes=20,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features=3,
    random_state=42,
    bootstrap=True,
    n_jobs=-1)

for_final.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, max_features=3, max_leaf_nodes=20,
                       min_samples_leaf=2, n_jobs=-1, random_state=42)

In [39]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred_final = for_final.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_final))
print(confusion_matrix(y_test, y_pred_final))
print(classification_report(y_test, y_pred_final))

Accuracy: 0.7922077922077922
[[84 13]
 [19 38]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.84        97
           1       0.75      0.67      0.70        57

    accuracy                           0.79       154
   macro avg       0.78      0.77      0.77       154
weighted avg       0.79      0.79      0.79       154

In [40]:
# Guardamos resultado
resultados_cv.append(evaluar_modelo('Random Forest', for_final, X_test, y_test))

##### AdaBoost

Cross validation

In [41]:
from sklearn.model_selection import GridSearchCV, KFold

base_tree = DecisionTreeClassifier(random_state=42)

ada = AdaBoostClassifier(
    n_estimators=30,
    estimator=base_tree,
    random_state=42)

param_grid = {
    'learning_rate': [0.2, 0.3, 0.5],
    'estimator__max_depth': [1, 2, 3],
    'estimator__min_samples_split': [2, 5, 10],
    'estimator__min_samples_leaf': [1, 2, 4]}

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

grid = GridSearchCV(
    estimator=ada,
    param_grid=param_grid,
    cv=kfold,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train, y_train)

print('Mejores hiperparámetros:', grid.best_params_)
print('Mejor score CV:', grid.best_score_)

Mejores hiperparámetros: {'estimator__max_depth': 3, 'estimator__min_samples_leaf': 1, 'estimator__min_samples_split': 5, 'learning_rate': 0.3}
Mejor score CV: 0.7731887890005288

Hemos validado nuestro modelo. Ahora construimos y entrenamos el modelo definitivo.

In [42]:
estimator = DecisionTreeClassifier(max_depth=3,
                                   min_samples_leaf=1,
                                   min_samples_split=5)

ada_final = AdaBoostClassifier(estimator = estimator,
                             n_estimators=30,
                             learning_rate=0.3,
                             random_state=42)

ada_final.fit(X_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=3,
                                                    min_samples_split=5),
                   learning_rate=0.3, n_estimators=30, random_state=42)

In [43]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred_final = ada_final.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_final))
print(confusion_matrix(y_test, y_pred_final))
print(classification_report(y_test, y_pred_final))

Accuracy: 0.7987012987012987
[[83 14]
 [17 40]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84        97
           1       0.74      0.70      0.72        57

    accuracy                           0.80       154
   macro avg       0.79      0.78      0.78       154
weighted avg       0.80      0.80      0.80       154

In [44]:
# Guardamos resultado
resultados_cv.append(evaluar_modelo('Ada Boost', ada_final, X_test, y_test))

##### GradientBoosting

Cross validation

In [45]:
grb = GradientBoostingClassifier(n_estimators=100,random_state=42)

param_grid = {
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [2, 3, 4],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'subsample': [1.0, 0.8, 0.6],  # 1.0 = boosting clásico, <1 = stochastic boosting
    'loss': ['log_loss', 'exponential']}

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

grid = GridSearchCV(
    estimator=grb,
    param_grid=param_grid,
    cv=kfold,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train, y_train)

print("Mejores hiperparámetros:", grid.best_params_)
print("Mejor score CV:", grid.best_score_)

Mejores hiperparámetros: {'learning_rate': 0.1, 'loss': 'log_loss', 'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 2, 'subsample': 0.8}
Mejor score CV: 0.7731623479640402

Hemos validado nuestro modelo. Ahora construimos y entrenamos el modelo definitivo.

In [46]:
grb_final = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=4,
    min_samples_split=2,
    min_samples_leaf=1,
    subsample=1.0,
    loss='log_loss',
    random_state=42)

grb_final.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, max_depth=4, random_state=42)

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred_final = grb_final.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_final))
print(confusion_matrix(y_test, y_pred_final))
print(classification_report(y_test, y_pred_final))

Accuracy: 0.7922077922077922
[[81 16]
 [16 41]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84        97
           1       0.72      0.72      0.72        57

    accuracy                           0.79       154
   macro avg       0.78      0.78      0.78       154
weighted avg       0.79      0.79      0.79       154

In [48]:
# Guardamos resultado
resultados_cv.append(evaluar_modelo('Gradient Boost', grb_final, X_test, y_test))

##### XGBoost

Cross validation

In [49]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, KFold

xgb = XGBClassifier(
    n_estimators=100,
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42)

param_grid = {
    'booster': ['gbtree', 'gblinear', 'dart'],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [3, 4, 5, 6]}

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

grid = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=kfold,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train, y_train)

print("Mejores hiperparámetros:", grid.best_params_)
print("Mejor score CV:", grid.best_score_)

Mejores hiperparámetros: {'booster': 'gbtree', 'learning_rate': 0.01, 'max_depth': 4}
Mejor score CV: 0.7650978318350079

Hemos validado nuestro modelo. Ahora construimos y entrenamos el modelo definitivo.

In [50]:
xgb_final = XGBClassifier(
    n_estimators=100,
    booster='gbtree',
    learning_rate=0.01,
    max_depth=4,
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42)

xgb_final.fit(X_train, y_train)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [51]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred_final = xgb_final.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_final))
print(confusion_matrix(y_test, y_pred_final))
print(classification_report(y_test, y_pred_final))

Accuracy: 0.7792207792207793
[[87 10]
 [24 33]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.84        97
           1       0.77      0.58      0.66        57

    accuracy                           0.78       154
   macro avg       0.78      0.74      0.75       154
weighted avg       0.78      0.78      0.77       154

In [52]:
# Guardamos resultado
resultados_cv.append(evaluar_modelo('XGBoost', xgb_final, X_test, y_test))

In [53]:
# Con los resultados guardados, montamos df
df_result_cv = pd.DataFrame(resultados_cv)
df_result_cv = df_result_cv.sort_values(by='accuracy', ascending=False)
df_result_cv

           modelo  accuracy  precision    recall        f1       auc
2       Ada Boost  0.798701   0.740741  0.701754  0.720721  0.857479
3  Gradient Boost  0.792208   0.719298  0.719298  0.719298  0.859107
1   Random Forest  0.792208   0.745098  0.666667  0.703704  0.851510
4         XGBoost  0.779221   0.767442  0.578947  0.660000  0.847260
0         Bagging  0.772727   0.789474  0.526316  0.631579  0.838126

### 10. Conclusiones finales

In [54]:
df_result

          modelo  accuracy  precision    recall        f1       auc
4        XGBoost  1.000000   1.000000  1.000000  1.000000  1.000000
3  GradientBoost  0.860495   0.838983  0.741573  0.787276  0.937393
1  Random Forest  0.839635   0.833333  0.674157  0.745342  0.920240
2       AdaBoost  0.807040   0.774194  0.629213  0.694215  0.888985
0        Bagging  0.777053   0.838028  0.445693  0.581907  0.868397

In [55]:
df_result_cv

           modelo  accuracy  precision    recall        f1       auc
2       Ada Boost  0.798701   0.740741  0.701754  0.720721  0.857479
3  Gradient Boost  0.792208   0.719298  0.719298  0.719298  0.859107
1   Random Forest  0.792208   0.745098  0.666667  0.703704  0.851510
4         XGBoost  0.779221   0.767442  0.578947  0.660000  0.847260
0         Bagging  0.772727   0.789474  0.526316  0.631579  0.838126

En la primera tabla, donde no se separó train/test, los modelos salen con resultados muy altos, incluso demasiado buenos. El caso más claro es XGBoost, que marca 1.00 en todo, que significa que el modelo se aprendió los datos de memoria (*overfitting*). Esto no refleja cómo funcionaría con datos nuevos y reales. Los demás modelos también salen mejor de lo que deberían, así que esa evaluación no es fiablee.

Cuando hacemos la evaluación bien, usando train/test y cross‑validation con el *gridsearch*, los resultados bajan a valores más realistas. Todos los modelos quedan más o menos en el mismo nivel, con accuracies alrededor de 0.79–0.80 y AUC cerca de 0.85. Aquí ya no hay un modelo 'mágico' muy superior al resto. De hecho, XGBoost, que antes parecía perfecto, baja bastante, lo que confirma que era el que más *overfitting* tenía.

En resumen, la comparación deja claro que si no separamos los datos, los modelos parecen mucho mejores de lo que son. Con una evaluación correcta, vemos su rendimiento real y podemos compararlos de verdad sin engañarnos.